import React, { useMemo, useState } from 'react';
import type { Ability, BackgroundDefinition, CharacterCreationSelection, ClassDefinition, Item, NewGameDefinition, PerkDefinition, RaceDefinition } from '@neon-ether/game-schema';
import type { ResolvedCharacterStats } from '@neon-ether/game-runtime';
import { ArrowLeft, Check, ChevronLeft, ChevronRight, Dices, UserRound } from 'lucide-react';
import { Button } from '@neon-ether/shared-ui';

type Step = 'identity'|'race'|'class'|'origin'|'attributes'|'skills'|'perks'|'review';
type Validation = {valid:boolean;reasons:string[];attributePointsRemaining:number;skillPointsRemaining:number};
interface Props {
  definition: NewGameDefinition; races: RaceDefinition[]; classes: ClassDefinition[]; backgrounds: BackgroundDefinition[]; perks: PerkDefinition[]; abilities: Ability[]; items: Item[];
  validate: (selection:CharacterCreationSelection)=>Validation; preview: (selection:CharacterCreationSelection)=>ResolvedCharacterStats|undefined;
  randomizeName:()=>string; adjustAttribute:(selection:CharacterCreationSelection,attribute:keyof CharacterCreationSelection['attributes'],delta:number)=>CharacterCreationSelection; adjustSkill:(selection:CharacterCreationSelection,skillId:string,delta:number)=>CharacterCreationSelection; onConfirm:(selection:CharacterCreationSelection)=>void; onCancel:()=>void;
}
const steps:Step[]=['identity','race','class','origin','attributes','skills','perks','review'];

export const CharacterCreator:React.FC<Props>=({definition,races,classes,backgrounds,perks,abilities,items,validate,preview,randomizeName,adjustAttribute,adjustSkill,onConfirm,onCancel})=>{
 const [step,setStep]=useState<Step>('identity');
 const [selection,setSelection]=useState<CharacterCreationSelection>(()=>({name:'',age:definition.defaultAge,portraitId:definition.portraits[0]?.id,raceId:definition.defaultRaceId,classId:'',backgroundId:'',attributes:Object.fromEntries(definition.attributeRules.map(rule=>[rule.attribute,rule.minimum])) as CharacterCreationSelection['attributes'],skills:Object.fromEntries(definition.skillRules.map(rule=>[rule.skillId,rule.minimum])),perkIds:[]}));
 const validation=useMemo(()=>validate(selection),[selection,validate]);const resolved=validation.valid?preview(selection):undefined;const index=steps.indexOf(step);
 const changeAttribute=(attribute:keyof CharacterCreationSelection['attributes'],delta:number)=>setSelection(current=>adjustAttribute(current,attribute,delta));
 const changeSkill=(skillId:string,delta:number)=>setSelection(current=>adjustSkill(current,skillId,delta));
 const togglePerk=(id:string)=>setSelection(current=>({...current,perkIds:current.perkIds.includes(id)?current.perkIds.filter(item=>item!==id):current.perkIds.length<definition.startingPerkCount?[...current.perkIds,id]:current.perkIds}));
 const canAdvance=step==='identity'?selection.name.trim().length>0&&selection.age>=definition.minimumAge&&selection.age<=definition.maximumAge:step==='race'?Boolean(races.find(race=>race.id===selection.raceId)?.isAvailable):step==='class'?Boolean(classes.find(value=>value.id===selection.classId)?.isAvailable):step==='origin'?Boolean(selection.backgroundId):step==='attributes'?validation.attributePointsRemaining===0:step==='skills'?validation.skillPointsRemaining===0:step==='perks'?selection.perkIds.length===definition.startingPerkCount:true;
 return <section className="ne-creator"><header><div><small>New game</small><h1>Character creation</h1></div><Button variant="ghost" onClick={onCancel} leftIcon={<ArrowLeft/>}>Main menu</Button></header><nav>{steps.map((value,itemIndex)=><span key={value} data-active={value===step} data-complete={itemIndex<index}>{itemIndex+1}<b>{value}</b></span>)}</nav><div className="ne-creator__body">
  {step==='identity'&&<IdentityStep definition={definition} selection={selection} setSelection={setSelection} randomizeName={randomizeName}/>}
  {step==='race'&&<OptionStep title="Race" subtitle="Ancestry" options={races} selectedId={selection.raceId} onSelect={id=>setSelection(value=>({...value,raceId:id}))}/>}
  {step==='class'&&<OptionStep title="Primary class" subtitle="Current discipline" options={classes} selectedId={selection.classId} onSelect={id=>setSelection(value=>({...value,classId:id}))}/>}
  {step==='origin'&&<OptionStep title="Origin" subtitle="Background" options={backgrounds.map(value=>({...value,isAvailable:true}))} selectedId={selection.backgroundId} onSelect={id=>setSelection(value=>({...value,backgroundId:id,perkIds:value.perkIds.filter(perkId=>{const perk=perks.find(item=>item.id===perkId);return !perk?.requiredBackgroundIds.length||perk.requiredBackgroundIds.includes(id)})}))}/>}
  {step==='attributes'&&<AllocationStep title="Attributes" remaining={validation.attributePointsRemaining}>{definition.attributeRules.map(rule=><AllocationRow key={rule.attribute} label={humanize(rule.attribute)} detail={`Min ${rule.minimum} · Max ${rule.maximum} · Cost ${rule.costPerPoint}`} value={selection.attributes[rule.attribute]} onDecrease={()=>changeAttribute(rule.attribute,-1)} onIncrease={()=>changeAttribute(rule.attribute,1)}/>)}</AllocationStep>}
  {step==='skills'&&<AllocationStep title="Skills" remaining={validation.skillPointsRemaining}>{definition.skillRules.map(rule=><AllocationRow key={rule.skillId} label={rule.name} detail={`Min ${rule.minimum} · Max ${rule.maximum} · Cost ${rule.costPerRank}`} value={selection.skills[rule.skillId]??rule.minimum} onDecrease={()=>changeSkill(rule.skillId,-1)} onIncrease={()=>changeSkill(rule.skillId,1)}/>)}</AllocationStep>}
  {step==='perks'&&<PerkStep perks={perks} selection={selection} count={definition.startingPerkCount} toggle={togglePerk}/>}
  {step==='review'&&<ReviewStep selection={selection} races={races} classes={classes} backgrounds={backgrounds} perks={perks} abilities={abilities} items={items} resolved={resolved} reasons={validation.reasons}/>}
 </div><footer><Button variant="ghost" disabled={index===0} onClick={()=>setStep(steps[index-1])} leftIcon={<ChevronLeft/>}>Back</Button><span>{step==='review'&&!validation.valid&&validation.reasons[0]}</span>{step==='review'?<Button disabled={!validation.valid} onClick={()=>onConfirm(selection)} rightIcon={<Check/>}>Confirm character</Button>:<Button disabled={!canAdvance} onClick={()=>setStep(steps[index+1])} rightIcon={<ChevronRight/>}>Continue</Button>}</footer></section>;
};

const IdentityStep:React.FC<{definition:NewGameDefinition;selection:CharacterCreationSelection;setSelection:React.Dispatch<React.SetStateAction<CharacterCreationSelection>>;randomizeName:()=>string}>=({definition,selection,setSelection,randomizeName})=><div className="ne-creator-panel ne-identity-step"><div className="ne-creator-portrait"><UserRound/></div><div><small>Identity</small><h2>Who enters the Glassline?</h2><label>Name<span><Button type="button" size="sm" variant="ether" onClick={()=>setSelection(value=>({...value,name:randomizeName()}))} leftIcon={<Dices/>}>Randomize name</Button></span><input autoFocus maxLength={40} value={selection.name} onChange={event=>setSelection(value=>({...value,name:event.target.value}))}/></label><label>Age <span>{definition.minimumAge}–{definition.maximumAge}</span><input type="number" min={definition.minimumAge} max={definition.maximumAge} value={selection.age} onChange={event=>setSelection(value=>({...value,age:Number(event.target.value)}))}/></label><fieldset><legend>Portrait</legend>{definition.portraits.map(portrait=><button type="button" key={portrait.id} data-selected={selection.portraitId===portrait.id} onClick={()=>setSelection(value=>({...value,portraitId:portrait.id}))}><UserRound/><span>{portrait.name}</span></button>)}</fieldset></div></div>;
const OptionStep:React.FC<{title:string;subtitle:string;options:Array<{id:string;name:string;description:string;isAvailable:boolean}>;selectedId:string;onSelect:(id:string)=>void}>=({title,subtitle,options,selectedId,onSelect})=><section className="ne-creator-panel"><header><div><small>{subtitle}</small><h2>{title}</h2></div></header><div className="ne-option-list">{options.map(option=><button type="button" key={option.id} disabled={!option.isAvailable} data-selected={selectedId===option.id} onClick={()=>option.isAvailable&&onSelect(option.id)}><strong>{option.name}</strong><p>{option.description}</p>{!option.isAvailable&&<small className="is-unmet">Not implemented yet</small>}</button>)}</div></section>;
const AllocationStep:React.FC<{title:string;remaining:number;children:React.ReactNode}>=({title,remaining,children})=><section className="ne-creator-panel"><header><div><small>Point allocation</small><h2>{title}</h2></div><strong>{remaining} points remaining</strong></header>{children}</section>;
const AllocationRow:React.FC<{label:string;detail:string;value:number;onDecrease:()=>void;onIncrease:()=>void}>=({label,detail,value,onDecrease,onIncrease})=><div className="ne-allocation-row"><span><b>{label}</b><small>{detail}</small></span><Button size="sm" variant="ghost" onClick={onDecrease}>−</Button><strong>{value}</strong><Button size="sm" variant="ghost" onClick={onIncrease}>+</Button></div>;
const PerkStep:React.FC<{perks:PerkDefinition[];selection:CharacterCreationSelection;count:number;toggle:(id:string)=>void}>=({perks,selection,count,toggle})=><section className="ne-creator-panel"><header><div><small>Starting perks</small><h2>Choose {count} edge{count===1?'':'s'}</h2></div><strong>{selection.perkIds.length}/{count}</strong></header><div className="ne-option-list">{perks.map(perk=>{const reason=perk.requiredBackgroundIds.length&&!perk.requiredBackgroundIds.includes(selection.backgroundId)?'Requires another background':perk.excludedPerkIds.some(id=>selection.perkIds.includes(id))?'Conflicts with selected perk':undefined;return <button type="button" key={perk.id} disabled={Boolean(reason)} title={reason} data-selected={selection.perkIds.includes(perk.id)} onClick={()=>toggle(perk.id)}><strong>{perk.name}</strong><p>{perk.description}</p>{reason&&<small className="is-unmet">{reason}</small>}</button>})}</div></section>;
const ReviewStep:React.FC<{selection:CharacterCreationSelection;races:RaceDefinition[];classes:ClassDefinition[];backgrounds:BackgroundDefinition[];perks:PerkDefinition[];abilities:Ability[];items:Item[];resolved?:ResolvedCharacterStats;reasons:string[]}>=({selection,races,classes,backgrounds,perks,abilities,items,resolved,reasons})=>{const race=races.find(value=>value.id===selection.raceId),playerClass=classes.find(value=>value.id===selection.classId),background=backgrounds.find(value=>value.id===selection.backgroundId);const abilityIds=[...new Set([...(race?.grantedAbilityIds??[]),...(race?.startingEffects.filter(effect=>effect.type==='setAbilityUnlocked').map(effect=>effect.abilityId)??[]),...(playerClass?.startingAbilityIds??[]),...(playerClass?.startingEffects.filter(effect=>effect.type==='setAbilityUnlocked').map(effect=>effect.abilityId)??[]),...(background?.startingEffects.filter(effect=>effect.type==='setAbilityUnlocked').map(effect=>effect.abilityId)??[])])];const equipment=[...(playerClass?.startingEquipment??[]),...(background?.startingItems??[])];return <div className="ne-creator-columns"><section className="ne-creator-panel ne-build-summary"><small>Final dossier</small><h2>{selection.name}</h2><p>Age {selection.age} · {race?.name} · {playerClass?.name} · {background?.name}</p><div className="ne-summary-stats">{Object.entries(resolved?.attributes??selection.attributes).map(([key,value])=><span key={key}><small>{humanize(key)}</small><strong>{value}</strong></span>)}</div><h3>Skills</h3><p>{Object.entries(selection.skills).map(([id,value])=>`${humanize(id)} ${value}`).join(' · ')}</p><h3>Perks</h3>{selection.perkIds.map(id=><p key={id}>{perks.find(perk=>perk.id===id)?.name}</p>)}</section><section className="ne-creator-panel"><small>Starting loadout</small><h2>{playerClass?.name}</h2><div className="ne-summary-list"><span>Race <strong>{race?.name}</strong></span><span>Background <strong>{background?.name}</strong></span>{abilityIds.map(id=><span key={id}>Ability <strong>{abilities.find(value=>value.id===id)?.name??'Unknown Ability'}</strong></span>)}{equipment.map((entry,index)=><span key={`${entry.itemId}-${index}`}>Equipment <strong>{items.find(value=>value.id===entry.itemId)?.name??'Unknown Item'} ×{entry.quantity}</strong></span>)}</div>{reasons.length>0&&<div className="ne-creator-errors">{reasons.map(reason=><p key={reason}>{reason}</p>)}</div>}</section></div>};
const humanize=(value:string)=>value.replace(/([a-z])([A-Z])/g,'$1 $2').replace(/_/g,' ');
