import React, { useMemo, useState } from 'react';
import type { Ability, BackgroundDefinition, CharacterCreationSelection, ClassDefinition, Item, NewGameDefinition, PerkDefinition, RaceDefinition } from '@neon-ether/game-schema';
import type { CharacterCreationPreview } from '@neon-ether/game-runtime';
import { ArrowLeft, Check, ChevronLeft, ChevronRight, Dices, UserRound } from 'lucide-react';
import { Button } from '@neon-ether/shared-ui';

type Step = 'identity'|'race'|'class'|'origin'|'attributes'|'skills'|'perks'|'review';
type Validation = {valid:boolean;reasons:string[];attributePointsRemaining:number;skillPointsRemaining:number};
interface Props {
  definition: NewGameDefinition; races: RaceDefinition[]; classes: ClassDefinition[]; backgrounds: BackgroundDefinition[]; perks: PerkDefinition[]; abilities: Ability[]; items: Item[];
  validate: (selection:CharacterCreationSelection)=>Validation; preview: (selection:CharacterCreationSelection)=>CharacterCreationPreview|undefined;
  randomizeName:()=>string; adjustAttribute:(selection:CharacterCreationSelection,attribute:keyof CharacterCreationSelection['attributes'],delta:number)=>CharacterCreationSelection; adjustSkill:(selection:CharacterCreationSelection,skillId:string,delta:number)=>CharacterCreationSelection; onConfirm:(selection:CharacterCreationSelection)=>void; onCancel:()=>void;
}
const steps:Step[]=['identity','race','class','origin','attributes','skills','perks','review'];

export const CharacterCreator:React.FC<Props>=({definition,races,classes,backgrounds,perks,abilities,items,validate,preview,randomizeName,adjustAttribute,adjustSkill,onConfirm,onCancel})=>{
 const [step,setStep]=useState<Step>('identity');
 const [selection,setSelection]=useState<CharacterCreationSelection>(()=>({name:'',age:definition.defaultAge,portraitId:definition.portraits[0]?.id,raceId:definition.defaultRaceId,classId:'',backgroundId:'',attributes:Object.fromEntries(definition.attributeRules.map(rule=>[rule.attribute,rule.minimum])) as CharacterCreationSelection['attributes'],skills:Object.fromEntries(definition.skillRules.map(rule=>[rule.skillId,rule.minimum])),perkIds:[]}));
 const validation=useMemo(()=>validate(selection),[selection,validate]);const buildPreview=validation.valid?preview(selection):undefined;const index=steps.indexOf(step);
 const changeAttribute=(attribute:keyof CharacterCreationSelection['attributes'],delta:number)=>setSelection(current=>adjustAttribute(current,attribute,delta));
 const changeSkill=(skillId:string,delta:number)=>setSelection(current=>adjustSkill(current,skillId,delta));
 const togglePerk=(id:string)=>setSelection(current=>({...current,perkIds:current.perkIds.includes(id)?current.perkIds.filter(item=>item!==id):current.perkIds.length<definition.startingPerkCount?[...current.perkIds,id]:current.perkIds}));
 const selectedRace=races.find(race=>race.id===selection.raceId),selectedClass=classes.find(value=>value.id===selection.classId);
 const canAdvance=step==='identity'?selection.name.trim().length>0&&selection.age>=definition.minimumAge&&selection.age<=definition.maximumAge:step==='race'?Boolean(selectedRace&&selectedRace.availability!=='NPC'):step==='class'?Boolean(selectedClass&&selectedClass.availability!=='NPC'):step==='origin'?Boolean(backgrounds.some(value=>value.id===selection.backgroundId)):step==='attributes'?validation.attributePointsRemaining===0:step==='skills'?validation.skillPointsRemaining===0:step==='perks'?selection.perkIds.length===definition.startingPerkCount:true;
 return <section className="ne-creator" data-step={step}><header><div><small>New game</small><h1>Character creation</h1></div><Button variant="ghost" onClick={onCancel} leftIcon={<ArrowLeft/>}>Main menu</Button></header><nav aria-label="Character creation steps">{steps.map((value,itemIndex)=><button type="button" key={value} data-active={value===step} data-complete={itemIndex<index} onClick={()=>setStep(value)}><span>{itemIndex+1}</span><b>{value}</b></button>)}</nav><div className="ne-creator__body">
  {step==='identity'&&<IdentityStep definition={definition} selection={selection} setSelection={setSelection} randomizeName={randomizeName}/>}
  {step==='race'&&<RaceStep races={races} selectedId={selection.raceId} onSelect={id=>setSelection(value=>({...value,raceId:id}))}/>}
  {step==='class'&&<ClassStep classes={classes} abilities={abilities} items={items} selectedId={selection.classId} onSelect={id=>setSelection(value=>({...value,classId:id}))}/>}
  {step==='origin'&&<OriginStep backgrounds={backgrounds} abilities={abilities} items={items} selectedId={selection.backgroundId} onSelect={id=>setSelection(value=>({...value,backgroundId:id,perkIds:value.perkIds.filter(perkId=>{const perk=perks.find(item=>item.id===perkId);return !perk?.requiredBackgroundIds.length||perk.requiredBackgroundIds.includes(id)})}))}/>}
  {step==='attributes'&&<AllocationStep title="Attributes" remaining={validation.attributePointsRemaining}>{definition.attributeRules.map(rule=>{const value=selection.attributes[rule.attribute];return <AllocationRow key={rule.attribute} label={humanize(rule.attribute)} description={rule.description} detail={`Min ${rule.minimum} · Max ${rule.maximum} · Cost ${rule.costPerPoint}`} value={value} decreaseDisabled={value<=rule.minimum} increaseDisabled={value>=rule.maximum||validation.attributePointsRemaining<rule.costPerPoint} onDecrease={()=>changeAttribute(rule.attribute,-1)} onIncrease={()=>changeAttribute(rule.attribute,1)}/>})}</AllocationStep>}
  {step==='skills'&&<AllocationStep title="Skills" remaining={validation.skillPointsRemaining}>{definition.skillRules.map(rule=>{const value=selection.skills[rule.skillId]??rule.minimum;return <AllocationRow key={rule.skillId} label={rule.name} description={rule.description} detail={`Min ${rule.minimum} · Max ${rule.maximum} · Cost ${rule.costPerRank}`} value={value} decreaseDisabled={value<=rule.minimum} increaseDisabled={value>=rule.maximum||validation.skillPointsRemaining<rule.costPerRank} onDecrease={()=>changeSkill(rule.skillId,-1)} onIncrease={()=>changeSkill(rule.skillId,1)}/>})}</AllocationStep>}
  {step==='perks'&&<PerkStep perks={perks} selection={selection} count={definition.startingPerkCount} toggle={togglePerk}/>}
  {step==='review'&&<ReviewStep selection={selection} races={races} classes={classes} backgrounds={backgrounds} perks={perks} abilities={abilities} items={items} preview={buildPreview} reasons={validation.reasons}/>}
 </div><footer><Button variant="ghost" disabled={index===0} onClick={()=>setStep(steps[index-1])} leftIcon={<ChevronLeft/>}>Previous</Button><span>{step==='review'&&!validation.valid&&validation.reasons[0]}</span>{step==='review'?<Button disabled={!validation.valid} onClick={()=>onConfirm(selection)} rightIcon={<Check/>}>Start game</Button>:<Button disabled={!canAdvance} onClick={()=>setStep(steps[index+1])} rightIcon={<ChevronRight/>}>Next</Button>}</footer></section>;
};

const IdentityStep:React.FC<{definition:NewGameDefinition;selection:CharacterCreationSelection;setSelection:React.Dispatch<React.SetStateAction<CharacterCreationSelection>>;randomizeName:()=>string}>=({definition,selection,setSelection,randomizeName})=><div className="ne-creator-panel ne-identity-step"><div className="ne-creator-portrait"><UserRound/></div><div><small>Identity</small><h2>Who enters the Glassline?</h2><label>Name<span><Button type="button" size="sm" variant="ether" onClick={()=>setSelection(value=>({...value,name:randomizeName()}))} leftIcon={<Dices/>}>Randomize</Button></span><input autoFocus maxLength={40} value={selection.name} onChange={event=>setSelection(value=>({...value,name:event.target.value}))}/></label><label>Age <span>{definition.minimumAge}–{definition.maximumAge}</span><input type="number" min={definition.minimumAge} max={definition.maximumAge} value={selection.age} onChange={event=>setSelection(value=>({...value,age:Number(event.target.value)}))}/></label><fieldset><legend>Portrait</legend>{definition.portraits.map(portrait=><button type="button" key={portrait.id} data-selected={selection.portraitId===portrait.id} onClick={()=>setSelection(value=>({...value,portraitId:portrait.id}))}><UserRound/><span>{portrait.name}</span></button>)}</fieldset></div></div>;
const RaceStep:React.FC<{races:RaceDefinition[];selectedId:string;onSelect:(id:string)=>void}>=({races,selectedId,onSelect})=><section className="ne-creator-panel ne-race-step"><header><div><small>Lineage</small><h2>Race</h2></div></header><div className="ne-option-list">{races.map(race=>{const available=race.availability!=='NPC';return <button type="button" key={race.id} disabled={!available} data-selected={selectedId===race.id} onClick={()=>available&&onSelect(race.id)}><span className="ne-race-art">{race.artwork?<img src={race.artwork} alt=""/>:<UserRound/>}</span><strong>{race.name}</strong><p>{race.description}</p><small>{race.grantedTraits.join(' · ')}</small>{race.attributeModifiers.length>0&&<small>{race.attributeModifiers.map(modifier=>`${humanize(modifier.target)} ${modifier.value>=0?'+':''}${modifier.value}`).join(' · ')}</small>}{!available&&<small className="is-unmet">Not implemented yet</small>}</button>})}</div></section>;
const ClassStep:React.FC<{classes:ClassDefinition[];abilities:Ability[];items:Item[];selectedId:string;onSelect:(id:string)=>void}>=({classes,abilities,items,selectedId,onSelect})=><section className="ne-creator-panel ne-class-step"><header><div><small>Profession</small><h2>Primary class</h2></div></header><div className="ne-option-list">{classes.filter(value=>value.availability!=='NPC').map(value=><button type="button" key={value.id} data-selected={selectedId===value.id} onClick={()=>onSelect(value.id)}><strong>{value.name}</strong><p>{value.description}</p><small>Signature · {value.startingAbilityIds.map(id=>abilities.find(ability=>ability.id===id)?.name??'Unknown Ability').join(' · ')}</small><small>Skills · {formatRecord(value.startingSkillModifiers)}</small><small>Identity · {value.startingModifiers.map(formatModifier).join(' · ')||'No starting modifier'}</small><small>Equipment · {value.startingEquipment.map(entry=>`${items.find(item=>item.id===entry.itemId)?.name??'Unknown Item'} ×${entry.quantity}`).join(' · ')||'None'}</small></button>)}</div></section>;
const OriginStep:React.FC<{backgrounds:BackgroundDefinition[];abilities:Ability[];items:Item[];selectedId:string;onSelect:(id:string)=>void}>=({backgrounds,abilities,items,selectedId,onSelect})=><section className="ne-creator-panel ne-origin-step"><header><div><small>History</small><h2>Origin</h2></div></header><div className="ne-option-list">{backgrounds.map(value=>{const abilityNames=value.startingEffects.flatMap(effect=>effect.type==='setAbilityUnlocked'?[abilities.find(ability=>ability.id===effect.abilityId)?.name??'Unknown Ability']:[]);return <button type="button" key={value.id} data-selected={selectedId===value.id} onClick={()=>onSelect(value.id)}><strong>{value.name}</strong><p>{value.description}</p><small>Skills · {formatRecord(value.startingSkills)}</small><small>Bonuses · {value.startingModifiers.map(formatModifier).join(' · ')||`${value.startingMoney} credits`}</small>{abilityNames.length>0&&<small>Ability · {abilityNames.join(' · ')}</small>}{value.startingItems.length>0&&<small>Gear · {value.startingItems.map(entry=>`${items.find(item=>item.id===entry.itemId)?.name??'Unknown Item'} ×${entry.quantity}`).join(' · ')}</small>}<em>{value.tags.join(' · ')}</em></button>})}</div></section>;
const AllocationStep:React.FC<{title:string;remaining:number;children:React.ReactNode}>=({title,remaining,children})=><section className="ne-creator-panel ne-allocation-step"><header><div><small>Point allocation</small><h2>{title}</h2></div><strong>{remaining} points remaining</strong></header>{children}</section>;
const AllocationRow:React.FC<{label:string;description:string;detail:string;value:number;decreaseDisabled:boolean;increaseDisabled:boolean;onDecrease:()=>void;onIncrease:()=>void}>=({label,description,detail,value,decreaseDisabled,increaseDisabled,onDecrease,onIncrease})=><div className="ne-allocation-row"><span><b>{label}</b><p>{description}</p><small>{detail}</small></span><Button size="sm" variant="ghost" disabled={decreaseDisabled} onClick={onDecrease}>−</Button><strong>{value}</strong><Button size="sm" variant="ghost" disabled={increaseDisabled} onClick={onIncrease}>+</Button></div>;
const PerkStep:React.FC<{perks:PerkDefinition[];selection:CharacterCreationSelection;count:number;toggle:(id:string)=>void}>=({perks,selection,count,toggle})=><section className="ne-creator-panel ne-perk-step"><header><div><small>Starting perks</small><h2>Choose your edge</h2></div><strong>Selected {selection.perkIds.length} / {count}</strong></header><div className="ne-perk-grid">{perks.map(perk=>{const reason=perk.requiredBackgroundIds.length&&!perk.requiredBackgroundIds.includes(selection.backgroundId)?'Requires another Origin':perk.excludedPerkIds.some(id=>selection.perkIds.includes(id))?'Conflicts with selected perk':undefined;return <button type="button" key={perk.id} data-category={perk.category} disabled={Boolean(reason)} title={reason} data-selected={selection.perkIds.includes(perk.id)} onClick={()=>toggle(perk.id)}><small>{perk.category}</small><strong>{perk.name}</strong><p>{perk.description}</p><span>{perk.modifiers.map(formatModifier).join(' · ')||perk.startingEffects.map(effect=>humanize(effect.type)).join(' · ')}</span>{perk.requirements.length>0&&<em>Requires · {perk.requirements.map(condition=>humanize(condition.type)).join(' · ')}</em>}{reason&&<em className="is-unmet">{reason}</em>}</button>})}</div></section>;
const ReviewStep:React.FC<{selection:CharacterCreationSelection;races:RaceDefinition[];classes:ClassDefinition[];backgrounds:BackgroundDefinition[];perks:PerkDefinition[];abilities:Ability[];items:Item[];preview?:CharacterCreationPreview;reasons:string[]}>=({selection,races,classes,backgrounds,perks,abilities,items,preview,reasons})=>{const race=races.find(value=>value.id===selection.raceId),playerClass=classes.find(value=>value.id===selection.classId),background=backgrounds.find(value=>value.id===selection.backgroundId);return <div className="ne-creator-columns ne-review-step"><section className="ne-creator-panel ne-build-summary"><small>Final dossier</small><h2>{selection.name}</h2><div className="ne-summary-list"><span>Age <strong>{selection.age}</strong></span><span>Race <strong>{race?.name}</strong></span><span>Primary class <strong>{playerClass?.name}</strong></span><span>Origin <strong>{background?.name}</strong></span></div><h3>Attributes</h3><div className="ne-summary-stats">{Object.entries(preview?.stats.attributes??selection.attributes).map(([key,value])=><span key={key}><small>{humanize(key)}</small><strong>{value}</strong></span>)}</div><h3>Skills</h3><p>{Object.entries(preview?.skills??selection.skills).map(([id,value])=>`${humanize(id)} ${value}`).join(' · ')}</p><h3>Perks</h3>{selection.perkIds.map(id=><p key={id}>{perks.find(perk=>perk.id===id)?.name}</p>)}</section><section className="ne-creator-panel"><small>Starting build</small><h2>{playerClass?.name}</h2><div className="ne-summary-list">{preview?.abilityIds.map(id=><span key={id}>Ability <strong>{abilities.find(value=>value.id===id)?.name??'Unknown Ability'}</strong></span>)}{preview?.inventory.map((entry,itemIndex)=><span key={`${entry.itemId}-${itemIndex}`}>Equipment <strong>{items.find(value=>value.id===entry.itemId)?.name??'Unknown Item'} ×{entry.quantity}</strong></span>)}</div>{reasons.length>0&&<div className="ne-creator-errors">{reasons.map(reason=><p key={reason}>{reason}</p>)}</div>}</section></div>};
const humanize=(value:string)=>value.replace(/([a-z])([A-Z])/g,'$1 $2').replace(/_/g,' ');
const formatModifier=(modifier:{target:string;value:number;operation:string})=>`${humanize(modifier.target)} ${modifier.operation==='multiply'?`×${modifier.value}`:`${modifier.value>=0?'+':''}${modifier.value}`}`;
const formatRecord=(record:Record<string,number>)=>Object.entries(record).map(([key,value])=>`${humanize(key)} ${value>=0?'+':''}${value}`).join(' · ')||'None';
