import React, { useMemo, useState } from 'react';
import type { BackgroundDefinition, CharacterCreationSelection, NewGameDefinition, PerkDefinition } from '@neon-ether/game-schema';
import type { ResolvedCharacterStats } from '@neon-ether/game-runtime';
import { ArrowLeft, Check, ChevronLeft, ChevronRight, Sparkles, UserRound } from 'lucide-react';
import { Button, ProgressBar } from '@neon-ether/shared-ui';

type Step = 'identity'|'aptitudes'|'origin'|'summary';
interface Props {
  definition: NewGameDefinition;
  backgrounds: BackgroundDefinition[];
  perks: PerkDefinition[];
  validate: (selection:CharacterCreationSelection)=>{valid:boolean;reasons:string[];attributePointsRemaining:number;skillPointsRemaining:number};
  preview: (selection:CharacterCreationSelection)=>ResolvedCharacterStats|undefined;
  onConfirm:(selection:CharacterCreationSelection)=>void;
  onCancel:()=>void;
}
const steps:Step[]=['identity','aptitudes','origin','summary'];

export const CharacterCreator:React.FC<Props>=({definition,backgrounds,perks,validate,preview,onConfirm,onCancel})=>{
 const [step,setStep]=useState<Step>('identity');
 const [selection,setSelection]=useState<CharacterCreationSelection>(()=>({name:'',age:definition.defaultAge,portraitId:definition.portraits[0]?.id,backgroundId:'',attributes:Object.fromEntries(definition.attributeRules.map(rule=>[rule.attribute,rule.minimum])) as CharacterCreationSelection['attributes'],skills:Object.fromEntries(definition.skillRules.map(rule=>[rule.skillId,rule.minimum])),perkIds:[]}));
 const validation=useMemo(()=>validate(selection),[selection,validate]);const resolved=validation.valid?preview(selection):undefined;const index=steps.indexOf(step);
 const adjustAttribute=(attribute:keyof CharacterCreationSelection['attributes'],delta:number)=>{const rule=definition.attributeRules.find(value=>value.attribute===attribute)!;const current=selection.attributes[attribute];if(current+delta<rule.minimum||current+delta>rule.maximum)return;setSelection(value=>({...value,attributes:{...value.attributes,[attribute]:current+delta}}))};
 const adjustSkill=(skillId:string,delta:number)=>{const rule=definition.skillRules.find(value=>value.skillId===skillId)!;const current=selection.skills[skillId]??rule.minimum;if(current+delta<rule.minimum||current+delta>rule.maximum)return;setSelection(value=>({...value,skills:{...value.skills,[skillId]:current+delta}}))};
 const togglePerk=(id:string)=>setSelection(value=>({...value,perkIds:value.perkIds.includes(id)?value.perkIds.filter(item=>item!==id):value.perkIds.length<definition.startingPerkCount?[...value.perkIds,id]:value.perkIds}));
 const canAdvance=step==='identity'?selection.name.trim().length>0&&selection.age>=definition.minimumAge&&selection.age<=definition.maximumAge:step==='aptitudes'?validation.attributePointsRemaining>=0&&validation.skillPointsRemaining>=0:step==='origin'?Boolean(selection.backgroundId)&&selection.perkIds.length===definition.startingPerkCount:true;
 return <section className="ne-creator"><header><div><small>New game</small><h1>Character creation</h1></div><Button variant="ghost" onClick={onCancel} leftIcon={<ArrowLeft/>}>Main menu</Button></header><nav>{steps.map((value,itemIndex)=><span key={value} data-active={value===step} data-complete={itemIndex<index}>{itemIndex+1}<b>{value}</b></span>)}</nav><div className="ne-creator__body">
 {step==='identity'&&<IdentityStep definition={definition} selection={selection} setSelection={setSelection}/>} 
 {step==='aptitudes'&&<AptitudesStep definition={definition} selection={selection} attributeRemaining={validation.attributePointsRemaining} skillRemaining={validation.skillPointsRemaining} adjustAttribute={adjustAttribute} adjustSkill={adjustSkill}/>} 
 {step==='origin'&&<OriginStep backgrounds={backgrounds} perks={perks} selection={selection} setSelection={setSelection} togglePerk={togglePerk}/>} 
 {step==='summary'&&<SummaryStep selection={selection} definition={definition} backgrounds={backgrounds} perks={perks} resolved={resolved} reasons={validation.reasons}/>} 
 </div><footer><Button variant="ghost" disabled={index===0} onClick={()=>setStep(steps[index-1])} leftIcon={<ChevronLeft/>}>Back</Button><span>{step==='summary'&&!validation.valid&&validation.reasons[0]}</span>{step==='summary'?<Button disabled={!validation.valid} onClick={()=>onConfirm(selection)} rightIcon={<Check/>}>Confirm character</Button>:<Button disabled={!canAdvance} onClick={()=>setStep(steps[index+1])} rightIcon={<ChevronRight/>}>Continue</Button>}</footer></section>;
};

const IdentityStep:React.FC<{definition:NewGameDefinition;selection:CharacterCreationSelection;setSelection:React.Dispatch<React.SetStateAction<CharacterCreationSelection>>}>=({definition,selection,setSelection})=><div className="ne-creator-panel ne-identity-step"><div className="ne-creator-portrait"><UserRound/></div><div><small>Identity</small><h2>Who enters the Glassline?</h2><label>Name<input autoFocus maxLength={40} value={selection.name} onChange={event=>setSelection(value=>({...value,name:event.target.value}))}/></label><label>Age <span>{definition.minimumAge}–{definition.maximumAge}</span><input type="number" min={definition.minimumAge} max={definition.maximumAge} value={selection.age} onChange={event=>setSelection(value=>({...value,age:Number(event.target.value)}))}/></label><fieldset><legend>Portrait</legend>{definition.portraits.map(portrait=><button type="button" key={portrait.id} data-selected={selection.portraitId===portrait.id} onClick={()=>setSelection(value=>({...value,portraitId:portrait.id}))}><UserRound/><span>{portrait.name}</span></button>)}</fieldset></div></div>;
const AptitudesStep:React.FC<{definition:NewGameDefinition;selection:CharacterCreationSelection;attributeRemaining:number;skillRemaining:number;adjustAttribute:(id:keyof CharacterCreationSelection['attributes'],delta:number)=>void;adjustSkill:(id:string,delta:number)=>void}>=({definition,selection,attributeRemaining,skillRemaining,adjustAttribute,adjustSkill})=><div className="ne-creator-columns"><section className="ne-creator-panel"><header><div><small>Attributes</small><h2>Core aptitudes</h2></div><strong>{attributeRemaining} points remaining</strong></header>{definition.attributeRules.map(rule=><div className="ne-allocation-row" key={rule.attribute}><span><b>{humanize(rule.attribute)}</b><small>Min {rule.minimum} · Max {rule.maximum} · Cost {rule.costPerPoint}</small></span><Button size="sm" variant="ghost" onClick={()=>adjustAttribute(rule.attribute,-1)}>−</Button><strong>{selection.attributes[rule.attribute]}</strong><Button size="sm" variant="ghost" onClick={()=>adjustAttribute(rule.attribute,1)}>+</Button></div>)}</section><section className="ne-creator-panel"><header><div><small>Skills</small><h2>Starting training</h2></div><strong>{skillRemaining} points remaining</strong></header>{definition.skillRules.length?definition.skillRules.map(rule=><div className="ne-allocation-row" key={rule.skillId}><span><b>{rule.name}</b><small>Max {rule.maximum} · Cost {rule.costPerRank}</small></span><Button size="sm" variant="ghost" onClick={()=>adjustSkill(rule.skillId,-1)}>−</Button><strong>{selection.skills[rule.skillId]}</strong><Button size="sm" variant="ghost" onClick={()=>adjustSkill(rule.skillId,1)}>+</Button></div>):<p>Starting skills are determined by background.</p>}</section></div>;
const OriginStep:React.FC<{backgrounds:BackgroundDefinition[];perks:PerkDefinition[];selection:CharacterCreationSelection;setSelection:React.Dispatch<React.SetStateAction<CharacterCreationSelection>>;togglePerk:(id:string)=>void}>=({backgrounds,perks,selection,setSelection,togglePerk})=><div className="ne-creator-columns"><section className="ne-creator-panel"><header><div><small>Background</small><h2>Origin</h2></div></header><div className="ne-option-list">{backgrounds.map(background=><button type="button" key={background.id} data-selected={selection.backgroundId===background.id} onClick={()=>setSelection(value=>({...value,backgroundId:background.id,perkIds:value.perkIds.filter(id=>{const perk=perks.find(item=>item.id===id);return !perk?.requiredBackgroundIds.length||perk.requiredBackgroundIds.includes(background.id)})}))}><strong>{background.name}</strong><p>{background.description}</p><small>{background.startingMoney} credits · {background.startingItems.length} starting item types</small></button>)}</div></section><section className="ne-creator-panel"><header><div><small>Starting perks</small><h2>Choose an edge</h2></div></header><div className="ne-option-list">{perks.map(perk=>{const reason=perk.requiredBackgroundIds.length&&!perk.requiredBackgroundIds.includes(selection.backgroundId)?'Requires another background':perk.excludedPerkIds.some(id=>selection.perkIds.includes(id))?'Conflicts with selected perk':undefined;return <button type="button" key={perk.id} disabled={Boolean(reason)} title={reason} data-selected={selection.perkIds.includes(perk.id)} onClick={()=>togglePerk(perk.id)}><strong>{perk.name}</strong><p>{perk.description}</p>{reason&&<small className="is-unmet">{reason}</small>}</button>})}</div></section></div>;
const SummaryStep:React.FC<{selection:CharacterCreationSelection;definition:NewGameDefinition;backgrounds:BackgroundDefinition[];perks:PerkDefinition[];resolved?:ResolvedCharacterStats;reasons:string[]}>=({selection,backgrounds,perks,resolved,reasons})=>{const background=backgrounds.find(value=>value.id===selection.backgroundId);return <div className="ne-creator-columns"><section className="ne-creator-panel ne-build-summary"><small>Final dossier</small><h2>{selection.name}</h2><p>Age {selection.age} · {background?.name}</p><div className="ne-summary-stats">{Object.entries(resolved?.attributes??selection.attributes).map(([key,value])=><span key={key}><small>{humanize(key)}</small><strong>{value}</strong></span>)}</div><h3>Perks</h3>{selection.perkIds.map(id=><p key={id}>{perks.find(perk=>perk.id===id)?.name}</p>)}</section><section className="ne-creator-panel"><small>Starting resources</small><h2>{background?.name}</h2><p>{background?.description}</p><div className="ne-summary-list"><span>Credits <strong>{background?.startingMoney??0}</strong></span>{background?.startingItems.map(item=><span key={item.itemId}>Starting item <strong>×{item.quantity}</strong></span>)}{resolved&&Object.entries(resolved.derivedStats).slice(0,6).map(([key,value])=><span key={key}>{humanize(key)} <strong>{value}</strong></span>)}</div>{reasons.length>0&&<div className="ne-creator-errors">{reasons.map(reason=><p key={reason}>{reason}</p>)}</div>}</section></div>};
const humanize=(value:string)=>value.replace(/([a-z])([A-Z])/g,'$1 $2').replace(/_/g,' ');
