import React, { useMemo, useState } from 'react';
import type { SaveGame, SaveLoadResult } from '@neon-ether/game-runtime';
import { ArrowLeft, Download, Gamepad2, Play, Save, Settings, Trash2 } from 'lucide-react';
import { Button, ConfirmationModal } from '@neon-ether/shared-ui';

type MenuPage = 'root'|'save'|'load'|'settings';
const slots = ['Slot 1 (Autosave)','Slot 2 (Manual)','Slot 3 (Manual)'];
const readSaves = () => slots.map((slot) => { try { const raw=localStorage.getItem(`neon_save_${slot}`); return {slot,save:raw?JSON.parse(raw) as SaveGame:undefined}; } catch { return {slot,save:undefined}; } });

export const MainMenu:React.FC<{onNewGame:()=>void;onContinue:(slot:string)=>SaveLoadResult}>=({onNewGame,onContinue})=>{
 const [page,setPage]=useState<MenuPage>('root');const [confirmNew,setConfirmNew]=useState(false);const saves=readSaves();const latest=[...saves].filter(x=>x.save).sort((a,b)=>Date.parse(b.save!.metadata.timestamp)-Date.parse(a.save!.metadata.timestamp))[0];
 return <div className="ne-main-menu"><div className="ne-main-menu__brand"><small>Dark fantasy role-playing game</small><h1>NEON <i>&amp;</i> ETHER</h1><p>Every light casts a second shadow.</p></div><section>{page==='root'?<><Button size="lg" onClick={()=>setConfirmNew(true)} leftIcon={<Gamepad2/>}>New game</Button><Button size="lg" variant="secondary" disabled={!latest} onClick={()=>latest&&onContinue(latest.slot)} leftIcon={<Play/>}>Continue</Button><Button size="lg" variant="secondary" onClick={()=>setPage('load')} leftIcon={<Download/>}>Load game</Button><Button size="lg" variant="ghost" onClick={()=>setPage('settings')} leftIcon={<Settings/>}>Settings</Button></>:page==='load'?<SaveLoadPanel mode="load" onBack={()=>setPage('root')} onLoad={onContinue}/>:<SettingsPanel onBack={()=>setPage('root')}/>}</section>{confirmNew&&<ConfirmationModal title="Start a new game?" description="Existing save files will be kept." onConfirm={onNewGame} onClose={()=>setConfirmNew(false)} confirmLabel="New game">Your current unsaved progress will be discarded.</ConfirmationModal>}</div>;
};

export const InGameMenu:React.FC<{onResume:()=>void;onMainMenu:()=>void;onSave:(slot:string)=>SaveGame;onLoad:(slot:string)=>SaveLoadResult}>=({onResume,onMainMenu,onSave,onLoad})=>{
 const [page,setPage]=useState<MenuPage>('root');const [confirmMain,setConfirmMain]=useState(false);const [revision,setRevision]=useState(0);void revision;
 return <div className="ne-menu-backdrop"><section className="ne-ingame-menu"><header><small>Paused</small><h1>NEON &amp; ETHER</h1></header>{page==='root'?<nav><Button size="lg" onClick={onResume}>Resume</Button><Button size="lg" variant="secondary" onClick={()=>setPage('save')} leftIcon={<Save/>}>Save game</Button><Button size="lg" variant="secondary" onClick={()=>setPage('load')} leftIcon={<Download/>}>Load game</Button><Button size="lg" variant="ghost" onClick={()=>setPage('settings')} leftIcon={<Settings/>}>Settings</Button><Button size="lg" variant="ghost" onClick={()=>setConfirmMain(true)}>Main menu</Button></nav>:page==='save'?<SaveLoadPanel mode="save" onBack={()=>setPage('root')} onSave={(slot)=>{onSave(slot);setRevision(v=>v+1)}}/>:page==='load'?<SaveLoadPanel mode="load" onBack={()=>setPage('root')} onLoad={onLoad}/>:<SettingsPanel onBack={()=>setPage('root')}/>}</section>{confirmMain&&<ConfirmationModal title="Return to main menu?" description="Save first if you want to keep recent progress." onConfirm={onMainMenu} onClose={()=>setConfirmMain(false)} confirmLabel="Main menu">Unsaved progress may be lost.</ConfirmationModal>}</div>;
};

const SaveLoadPanel:React.FC<{mode:'save'|'load';onBack:()=>void;onSave?:(slot:string)=>void;onLoad?:(slot:string)=>SaveLoadResult}>=({mode,onBack,onSave,onLoad})=>{
 const [confirmDelete,setConfirmDelete]=useState<string>();const [revision,setRevision]=useState(0);const saves=useMemo(readSaves,[revision]);return <div className="ne-save-panel"><header><Button variant="ghost" size="sm" onClick={onBack} leftIcon={<ArrowLeft/>}>Back</Button><h2>{mode==='save'?'Save game':'Load game'}</h2></header><div>{saves.map(({slot,save})=><article key={slot}><div><strong>{save?.metadata.slotName??slot}</strong>{save?<><span>{new Date(save.metadata.timestamp).toLocaleString()}</span><small>{save.metadata.playerName} · Level {save.metadata.playerLevel}</small><small>Playtime {formatTime(save.metadata.playtimeSeconds)}</small></>:<span>Empty slot</span>}</div><div>{mode==='save'?<Button size="sm" onClick={()=>onSave?.(slot)}>Save</Button>:<Button size="sm" disabled={!save} onClick={()=>onLoad?.(slot)}>Load</Button>}{save&&<Button size="sm" variant="ghost" onClick={()=>setConfirmDelete(slot)} title="Delete save"><Trash2/></Button>}</div></article>)}</div>{confirmDelete&&<ConfirmationModal danger title="Delete this save?" onConfirm={()=>{localStorage.removeItem(`neon_save_${confirmDelete}`);setConfirmDelete(undefined);setRevision(v=>v+1)}} onClose={()=>setConfirmDelete(undefined)} confirmLabel="Delete">This cannot be undone.</ConfirmationModal>}</div>;
};
const SettingsPanel:React.FC<{onBack:()=>void}>=({onBack})=>{const [reduced,setReduced]=useState(localStorage.getItem('neon_reduced_motion')==='true');return <div className="ne-settings-panel"><header><Button variant="ghost" size="sm" onClick={onBack} leftIcon={<ArrowLeft/>}>Back</Button><h2>Settings</h2></header><label><span><strong>Reduced motion</strong><small>Minimize interface animation.</small></span><input type="checkbox" checked={reduced} onChange={e=>{setReduced(e.target.checked);localStorage.setItem('neon_reduced_motion',String(e.target.checked));document.documentElement.dataset.reducedMotion=String(e.target.checked)}}/></label></div>};
const formatTime=(seconds:number)=>`${Math.floor(seconds/3600)}h ${Math.floor(seconds%3600/60)}m`;
