import React, { useMemo, useState } from 'react';
import type { SaveGame, SaveLoadResult } from '@neon-ether/game-runtime';
import { ArrowLeft, Download, Gamepad2, Play, Save, Settings, Trash2 } from 'lucide-react';
import { Button, ConfirmationModal, ScreenEffects } from '@neon-ether/shared-ui';
import { readVisualPreferences, saveVisualPreferences, type VisualPreferences } from '../presentation/visual-preferences.ts';

type MenuPage = 'root'|'save'|'load'|'settings';
const slots = [{id:'autosave-1',label:'Autosave',kind:'Autosave'},{id:'manual-1',label:'Manual Slot 1',kind:'Manual'},{id:'manual-2',label:'Manual Slot 2',kind:'Manual'},{id:'manual-3',label:'Manual Slot 3',kind:'Manual'}] as const;
const readSaves = () => slots.map((slot) => { try { const raw=localStorage.getItem(`neon_save_${slot.id}`); return {...slot,save:raw?JSON.parse(raw) as SaveGame:undefined}; } catch { return {...slot,save:undefined}; } });

export const MainMenu:React.FC<{onNewGame:()=>void;onContinue:(slot:string)=>SaveLoadResult}>=({onNewGame,onContinue})=>{
 const [page,setPage]=useState<MenuPage>('root');const [confirmNew,setConfirmNew]=useState(false);const saves=readSaves();const latest=[...saves].filter(x=>x.save).sort((a,b)=>Date.parse(b.save!.metadata.timestamp)-Date.parse(a.save!.metadata.timestamp))[0];
 return <div className="ne-main-menu"><ScreenEffects/><div className="ne-main-menu__brand"><small>Dark fantasy role-playing game</small><h1>NEON <i>&amp;</i> ETHER</h1><p>Every light casts a second shadow.</p></div><section>{page==='root'?<><Button className="ne-menu-action is-new" size="lg" onClick={()=>setConfirmNew(true)} leftIcon={<Gamepad2/>}>New game</Button><Button className="ne-menu-action is-continue" size="lg" variant="secondary" disabled={!latest} onClick={()=>latest&&onContinue(latest.id)} leftIcon={<Play/>}>Continue</Button><Button className="ne-menu-action is-load" size="lg" variant="secondary" onClick={()=>setPage('load')} leftIcon={<Download/>}>Load game</Button><Button className="ne-menu-action is-settings" size="lg" variant="ghost" onClick={()=>setPage('settings')} leftIcon={<Settings/>}>Settings</Button></>:page==='load'?<SaveLoadPanel mode="load" onBack={()=>setPage('root')} onLoad={onContinue}/>:<SettingsPanel onBack={()=>setPage('root')}/>}</section>{confirmNew&&<ConfirmationModal title="Start a new game?" description="Existing save files will be kept." onConfirm={onNewGame} onClose={()=>setConfirmNew(false)} confirmLabel="New game">Your current unsaved progress will be discarded.</ConfirmationModal>}</div>;
};

export const InGameMenu:React.FC<{onResume:()=>void;onMainMenu:()=>void;onSave:(slot:string)=>SaveGame;onLoad:(slot:string)=>SaveLoadResult}>=({onResume,onMainMenu,onSave,onLoad})=>{
 const [page,setPage]=useState<MenuPage>('root');const [confirmMain,setConfirmMain]=useState(false);
 return <div className="ne-menu-backdrop"><section className="ne-ingame-menu"><header><small>Paused</small><h1>NEON &amp; ETHER</h1></header>{page==='root'?<nav><Button size="lg" onClick={onResume}>Resume</Button><Button size="lg" variant="secondary" onClick={()=>setPage('save')} leftIcon={<Save/>}>Save game</Button><Button size="lg" variant="secondary" onClick={()=>setPage('load')} leftIcon={<Download/>}>Load game</Button><Button size="lg" variant="ghost" onClick={()=>setPage('settings')} leftIcon={<Settings/>}>Settings</Button><Button size="lg" variant="ghost" onClick={()=>setConfirmMain(true)}>Main menu</Button></nav>:page==='save'?<SaveLoadPanel mode="save" onBack={()=>setPage('root')} onSave={onSave}/>:page==='load'?<SaveLoadPanel mode="load" onBack={()=>setPage('root')} onLoad={onLoad}/>:<SettingsPanel onBack={()=>setPage('root')}/>}</section>{confirmMain&&<ConfirmationModal title="Return to main menu?" description="Save first if you want to keep recent progress." onConfirm={onMainMenu} onClose={()=>setConfirmMain(false)} confirmLabel="Main menu">Unsaved progress may be lost.</ConfirmationModal>}</div>;
};

const SaveLoadPanel:React.FC<{mode:'save'|'load';onBack:()=>void;onSave?:(slot:string)=>SaveGame;onLoad?:(slot:string)=>SaveLoadResult}>=({mode,onBack,onSave,onLoad})=>{
 const [confirmDelete,setConfirmDelete]=useState<string>();const [revision,setRevision]=useState(0);const [feedback,setFeedback]=useState<string>();const saves=useMemo(readSaves,[revision]);
 const saveSlot=(id:string)=>{const saved=onSave?.(id);if(saved){setRevision(value=>value+1);setFeedback('GAME SAVED')}};
 return <div className="ne-save-panel"><header><Button variant="ghost" size="sm" onClick={onBack} leftIcon={<ArrowLeft/>}>Back</Button><h2>{mode==='save'?'Save game':'Load game'}</h2>{feedback&&<span className="text-emerald-300">{feedback}</span>}</header><div>{saves.map(({id,label,kind,save})=><article key={id}><div><strong>{save?.metadata.slotName??label}</strong><b>{save?.metadata.saveKind??kind} save</b>{save?<><span>{new Date(save.metadata.timestamp).toLocaleString()}</span><small>{save.metadata.playerName} · Level {save.metadata.playerLevel}{save.metadata.currentLocationName?` · ${save.metadata.currentLocationName}`:''}</small><small>Playtime {formatTime(save.metadata.playtimeSeconds)}</small></>:<span>Empty slot</span>}</div><div>{mode==='save'?(kind==='Autosave'?<small>System managed</small>:<Button size="sm" onClick={()=>saveSlot(id)}>{save?'Overwrite':'Save'}</Button>):<Button size="sm" disabled={!save} onClick={()=>onLoad?.(id)}>Load</Button>}{save&&kind==='Manual'&&<Button size="sm" variant="ghost" onClick={()=>setConfirmDelete(id)} title="Delete save"><Trash2/></Button>}</div></article>)}</div>{confirmDelete&&<ConfirmationModal danger title="Delete this save?" onConfirm={()=>{localStorage.removeItem(`neon_save_${confirmDelete}`);setConfirmDelete(undefined);setRevision(v=>v+1)}} onClose={()=>setConfirmDelete(undefined)} confirmLabel="Delete">This cannot be undone.</ConfirmationModal>}</div>;
};
const SettingsPanel:React.FC<{onBack:()=>void}>=({onBack})=>{const [visuals,setVisuals]=useState<VisualPreferences>(readVisualPreferences);const update=(next:VisualPreferences)=>{setVisuals(next);saveVisualPreferences(next)};return <div className="ne-settings-panel"><header><Button variant="ghost" size="sm" onClick={onBack} leftIcon={<ArrowLeft/>}>Back</Button><h2>Settings</h2></header><label><span><strong>Visual effects</strong><small>Atmosphere density and screen texture.</small></span><select value={visuals.quality} onChange={event=>update({...visuals,quality:event.target.value as VisualPreferences['quality']})}><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option></select></label><label><span><strong>Scanlines</strong><small>Subtle CRT display texture.</small></span><input type="checkbox" checked={visuals.scanlines} onChange={event=>update({...visuals,scanlines:event.target.checked})}/></label><label><span><strong>Reduced motion</strong><small>Minimize interface animation.</small></span><input type="checkbox" checked={visuals.reducedMotion} onChange={event=>update({...visuals,reducedMotion:event.target.checked})}/></label></div>};
const formatTime=(seconds:number)=>`${Math.floor(seconds/3600)}h ${Math.floor(seconds%3600/60)}m`;
