import React from 'react';
import type { BaseState } from '@neon-ether/game-schema';
import { ArrowLeft, Home, Lock, PackageOpen, Users, Wrench } from 'lucide-react';
import { Panel } from './Panel.tsx';

/** Pure presentation for the logical BaseState; definitions and mutations stay in runtime. */
export const BaseScreen: React.FC<{ base: BaseState; onReturn: () => void }> = ({ base, onReturn }) => { const slots=Object.values(base.roomSlots) as Array<{slotId:string;slotType:string;roomInstanceId:string|null;isLocked:boolean}>; return <div className="flex h-full w-full flex-col gap-4 font-mono">
  <header className="flex items-center justify-between rounded-xl border border-zinc-800 bg-zinc-950/90 p-3"><button type="button" onClick={onReturn} className="flex items-center gap-2 rounded border border-zinc-700 px-3 py-2 text-xs text-cyan-300"><ArrowLeft className="h-4 w-4"/> RETURN TO MAP</button><div className="text-right"><p className="text-xs font-bold text-white">{base.name || base.baseId}</p><p className="text-[9px] text-zinc-500">BASE MANAGEMENT</p></div></header>
  <div className="grid flex-1 gap-4 lg:grid-cols-[1fr_2fr]"><Panel title="BASE RESOURCES" subtitle={`${base.residentNpcIds.length} RESIDENTS`}><div className="space-y-2">{Object.entries(base.resources).map(([id,value])=><div key={id} className="flex justify-between rounded border border-zinc-800 p-2 text-xs"><span>{id}</span><b className="text-cyan-300">{value}</b></div>)}<div className="flex items-center gap-2 text-xs text-zinc-400"><PackageOpen className="h-4 w-4"/> Storage {base.storage.items.length}/{base.storage.capacity}</div><div className="flex items-center gap-2 text-xs text-zinc-400"><Users className="h-4 w-4"/> Residents {base.residentNpcIds.length}</div></div></Panel><Panel title="LOGICAL ROOM LAYOUT" subtitle={`${Object.keys(base.rooms).length} BUILT ROOMS`}><div className="grid gap-3 md:grid-cols-2">{slots.map((slot)=>{const room=slot.roomInstanceId?base.rooms[slot.roomInstanceId]:undefined;return <article key={slot.slotId} className="rounded-xl border border-zinc-700 bg-black/40 p-3"><div className="flex justify-between">{room?<Home className="h-4 w-4 text-cyan-300"/>:slot.isLocked?<Lock className="h-4 w-4 text-amber-400"/>:<Wrench className="h-4 w-4 text-zinc-500"/>}<span className="text-[9px] text-zinc-500">{slot.slotType}</span></div><p className="mt-2 text-xs font-bold text-white">{room?.definitionId ?? (slot.isLocked?'LOCKED SLOT':'FREE SLOT')}</p>{room&&<p className="text-[9px] text-purple-300">Level {room.level} · {room.installedUpgradeIds.length} upgrades</p>}</article>})}</div></Panel></div>
</div>; };
