import React, { useState } from 'react';
import type { BaseJobDefinition, BaseRoomDefinition, BaseState, BaseUpgradeDefinition, NpcRuntimeState } from '@neon-ether/game-schema';
import type { BaseOption } from '@neon-ether/game-runtime';
import { ArrowLeft, Home, Lock, PackageOpen, Users, Wrench } from 'lucide-react';
import { Panel } from './Panel.tsx';

export interface BaseScreenProps {
  base:BaseState; onReturn:()=>void;
  roomOptions:(slotId:string)=>BaseOption<BaseRoomDefinition>[]; upgradeOptions:(roomId:string)=>BaseOption<BaseUpgradeDefinition>[];
  residents:Array<{runtime:NpcRuntimeState;name:string}>; jobs:BaseJobDefinition[];
  onBuildRoom:(slotId:string,definitionId:string)=>void; onInstallUpgrade:(roomId:string,upgradeId:string)=>void;
  onAssign:(npcId:string,jobId:string,roomId:string)=>void;
}
/** Pure presentation and typed command dispatch for the generic logical base runtime. */
export const BaseScreen:React.FC<BaseScreenProps>=({base,onReturn,roomOptions,upgradeOptions,residents,jobs,onBuildRoom,onInstallUpgrade,onAssign})=>{
 const [choices,setChoices]=useState<Record<string,string>>({});const choose=(key:string,value:string)=>setChoices(current=>({...current,[key]:value}));
 const slots=Object.values(base.roomSlots) as Array<{slotId:string;slotType:string;roomInstanceId:string|null;isLocked:boolean}>;
 return <div className="flex h-full w-full flex-col gap-4 font-mono"><header className="flex items-center justify-between rounded-xl border border-zinc-800 bg-zinc-950/90 p-3"><button type="button" onClick={onReturn} className="flex items-center gap-2 rounded border border-zinc-700 px-3 py-2 text-xs text-cyan-300"><ArrowLeft className="h-4 w-4"/> RETURN TO MAP</button><div className="text-right"><p className="text-xs font-bold text-white">{base.name||base.baseId}</p><p className="text-[9px] text-zinc-500">BASE MANAGEMENT</p></div></header>
 <div className="grid flex-1 gap-4 lg:grid-cols-[1fr_2fr]"><Panel title="BASE RESOURCES" subtitle={`${base.residentNpcIds.length} RESIDENTS`}><div className="space-y-2">{Object.entries(base.resources).map(([id,value])=><div key={id} className="flex justify-between rounded border border-zinc-800 p-2 text-xs"><span>{id}</span><b className="text-cyan-300">{value}</b></div>)}<div className="flex items-center gap-2 text-xs text-zinc-400"><PackageOpen className="h-4 w-4"/> Storage {base.storage.items.length}/{base.storage.capacity}</div><div className="flex items-center gap-2 text-xs text-zinc-400"><Users className="h-4 w-4"/> Residents {base.residentNpcIds.length}</div></div></Panel>
 <Panel title="LOGICAL ROOM LAYOUT" subtitle={`${Object.keys(base.rooms).length} BUILT ROOMS`}><div className="grid gap-3 md:grid-cols-2">{slots.map(slot=>{const room=slot.roomInstanceId?base.rooms[slot.roomInstanceId]:undefined;const rooms=roomOptions(slot.slotId);const upgrades=room?upgradeOptions(room.roomId):[];return <article key={slot.slotId} className="rounded-xl border border-zinc-700 bg-black/40 p-3"><div className="flex justify-between">{room?<Home className="h-4 w-4 text-cyan-300"/>:slot.isLocked?<Lock className="h-4 w-4 text-amber-400"/>:<Wrench className="h-4 w-4 text-zinc-500"/>}<span className="text-[9px] text-zinc-500">{slot.slotType}</span></div><p className="mt-2 text-xs font-bold text-white">{room?.definitionId??(slot.isLocked?'LOCKED SLOT':'FREE SLOT')}</p>{room?<><p className="text-[9px] text-purple-300">Level {room.level} · {room.installedUpgradeIds.length} upgrades</p><select value={choices[`up:${room.roomId}`]??''} onChange={event=>choose(`up:${room.roomId}`,event.target.value)} className="mt-2 w-full rounded bg-zinc-950 p-1 text-[10px]"><option value="">Choose upgrade…</option>{upgrades.map(option=><option key={option.definition.id} value={option.definition.id} disabled={!option.isAvailable}>{option.definition.name}{option.isAvailable?'':` — ${option.unavailableReasons[0]}`}</option>)}</select><button disabled={!choices[`up:${room.roomId}`]} onClick={()=>onInstallUpgrade(room.roomId,choices[`up:${room.roomId}`])} className="mt-1 rounded border border-purple-500/40 px-2 py-1 text-[10px] text-purple-300 disabled:opacity-30">Install</button></>:!slot.isLocked&&<><select value={choices[`room:${slot.slotId}`]??''} onChange={event=>choose(`room:${slot.slotId}`,event.target.value)} className="mt-2 w-full rounded bg-zinc-950 p-1 text-[10px]"><option value="">Choose room…</option>{rooms.map(option=><option key={option.definition.id} value={option.definition.id} disabled={!option.isAvailable}>{option.definition.name}{option.isAvailable?'':` — ${option.unavailableReasons[0]}`}</option>)}</select><button disabled={!choices[`room:${slot.slotId}`]} onClick={()=>onBuildRoom(slot.slotId,choices[`room:${slot.slotId}`])} className="mt-1 rounded border border-cyan-500/40 px-2 py-1 text-[10px] text-cyan-300 disabled:opacity-30">Build</button></>}</article>})}</div>
 {residents.length>0&&<div className="mt-4 space-y-2"><h3 className="text-[10px] uppercase text-cyan-400">Residents & jobs</h3>{residents.map(({runtime,name})=><article key={runtime.npcId} className="grid gap-2 rounded border border-zinc-800 p-2 md:grid-cols-4"><span className="text-xs">{name}</span><select value={choices[`job:${runtime.npcId}`]??runtime.assignment.jobId??''} onChange={e=>choose(`job:${runtime.npcId}`,e.target.value)} className="rounded bg-zinc-950 p-1 text-[10px]"><option value="">Choose job…</option>{jobs.map(job=><option key={job.id} value={job.id}>{job.name}</option>)}</select><select value={choices[`assign:${runtime.npcId}`]??runtime.assignment.roomId??''} onChange={e=>choose(`assign:${runtime.npcId}`,e.target.value)} className="rounded bg-zinc-950 p-1 text-[10px]"><option value="">Choose room…</option>{(Object.values(base.rooms) as import('@neon-ether/game-schema').BaseRoomRuntimeState[]).map(room=><option key={room.roomId} value={room.roomId}>{room.definitionId}</option>)}</select><button onClick={()=>onAssign(runtime.npcId,choices[`job:${runtime.npcId}`]??runtime.assignment.jobId??'',choices[`assign:${runtime.npcId}`]??runtime.assignment.roomId??'')} className="rounded border border-cyan-500/40 px-2 text-[10px] text-cyan-300">Assign</button></article>)}</div>}
 </Panel></div></div>;
};
