import React, { useState } from 'react';
import type { InventoryState, Item, RecipeDefinition } from '@neon-ether/game-schema';
import { ArrowLeft, Check, Hammer, Lock, PackageOpen } from 'lucide-react';
import { Button } from './Button.tsx';

export const CraftingScreen:React.FC<{recipes:RecipeDefinition[];availableIds:Set<string>;inventory:InventoryState;items:Item[];onCraft:(id:string)=>void;onReturn:()=>void}>=({recipes,availableIds,inventory,items,onCraft,onReturn})=>{
 const [selectedId,setSelectedId]=useState(recipes[0]?.id);const selected=recipes.find(r=>r.id===selectedId);const itemMap=new Map<string, Item>(items.map(i=>[i.id,i]));const counts=new Map(inventory.items.map(slot=>[slot.itemId,slot.quantity]));
 return <section className="ne-context-screen"><header><div><Hammer/><span>Safehouse workshop</span></div><small>Fabrication interface</small></header><div className="ne-crafting-grid"><section className="ne-recipe-list"><h2>Recipes</h2>{recipes.map(recipe=><button type="button" key={recipe.id} data-selected={recipe.id===selectedId} onClick={()=>setSelectedId(recipe.id)}>{availableIds.has(recipe.id)?<Check/>:<Lock/>}<span><strong>{recipe.name}</strong><small>{recipe.category} · {recipe.timeCost.turns} turn</small></span></button>)}</section><section className="ne-recipe-detail">{selected&&<><div><span>Output</span><h2>{selected.name}</h2><p>{selected.description}</p></div><div className="ne-materials"><h3>Required materials</h3>{selected.inputs.map(input=><div key={input.itemId} data-met={(counts.get(input.itemId)??0)>=input.quantity}><PackageOpen/><span>{itemMap.get(input.itemId)?.name??input.itemId}</span><strong>{counts.get(input.itemId)??0} / {input.quantity}</strong></div>)}</div><div className="ne-output"><small>Produces</small><strong>{selected.output.quantity} × {itemMap.get(selected.output.itemId)?.name??selected.output.itemId}</strong></div><Button onClick={()=>onCraft(selected.id)} disabled={!availableIds.has(selected.id)}>Craft item</Button></>}</section></div><footer className="ne-context-footer"><span/><Button variant="ghost" onClick={onReturn} leftIcon={<ArrowLeft/>}>Return</Button></footer></section>;
};
