import type { Item, ShopDefinition } from '@neon-ether/game-schema';
import type { ContentRegistry } from '../content/content-registry.ts';
import type { GameState } from '../state/game-state.ts';
import { ConditionRegistry, defaultConditionRegistry } from '../conditions/condition-registry.ts';
import { evaluateConditions } from '../conditions/condition-evaluator.ts';
import { InventorySystem } from '../inventory/inventory-system.ts';
import { DiceRoller, type RandomSource } from '@neon-ether/engine';
export interface ShopItemView {item:Item;quantity:number|null;buyPrice:number;sellPrice:number}
export interface ShopView {shop:ShopDefinition;available:boolean;items:ShopItemView[]}
export interface TradeResult {success:boolean;shopId:string;itemId:string;quantity:number;creditsChanged:number;reason?:string}
/** Data-driven pricing, stock, restock, and trading with no merchant-specific branches. */
export class EconomySystem {
 private inventory:InventorySystem;
 constructor(private readonly content:ContentRegistry,private readonly conditions:ConditionRegistry=defaultConditionRegistry,private readonly random:RandomSource=new DiceRoller(1337)){this.inventory=new InventorySystem(content);}
 getShop(shopId:string,state:GameState):ShopView|undefined{const shop=this.content.shops.get(shopId);if(!shop)return;this.restock(shop,state);const available=evaluateConditions(shop.availabilityConditions,{state,contentRegistry:this.content,rollRandom:(min,max)=>this.random.integer(min,max)},this.conditions).allMet;return {shop,available,items:shop.inventory.flatMap(entry=>{const item=this.content.getItem(entry.itemId);return item?[{item,quantity:shop.inventorySource==='unlimited'?null:(state.shops[shop.id]?.stock[item.id]??0),buyPrice:this.price(shop,item,'buy',state),sellPrice:this.price(shop,item,'sell',state)}]:[]})};}
 buy(shopId:string,itemId:string,quantity:number,state:GameState):TradeResult{return this.trade('buy',shopId,itemId,quantity,state);}
 sell(shopId:string,itemId:string,quantity:number,state:GameState):TradeResult{return this.trade('sell',shopId,itemId,quantity,state);}
 private trade(mode:'buy'|'sell',shopId:string,itemId:string,quantity:number,state:GameState):TradeResult{const fail=(reason:string):TradeResult=>({success:false,shopId,itemId,quantity,creditsChanged:0,reason});if(!Number.isInteger(quantity)||quantity<1)return fail('Quantity must be a positive integer.');const view=this.getShop(shopId,state);if(!view?.available)return fail('Shop is unavailable.');const item=this.content.getItem(itemId);if(!item)return fail('Item not found.');const shop=view.shop,rule=mode==='buy'?shop.buyRules:shop.sellRules;if(!rule.enabled||!evaluateConditions(rule.conditions,{state,contentRegistry:this.content,rollRandom:(min,max)=>this.random.integer(min,max)},this.conditions).allMet)return fail(`${mode} rule is unavailable.`);if(rule.categories.length&&!rule.categories.includes(item.category))return fail('Item category is not traded.');if(rule.requiredTags.length&&!rule.requiredTags.every(tag=>item.tags.includes(tag)))return fail('Item tags are not traded.');const price=this.price(shop,item,mode,state)*quantity;const runtime=state.shops[shop.id];if(mode==='buy'){if(shop.inventorySource==='stock'&&(runtime.stock[itemId]??0)<quantity)return fail('Not enough stock.');if(state.player.inventory.credits<price)return fail('Not enough credits.');const simulated=structuredClone(state.player.inventory);if(!this.inventory.add(simulated,itemId,quantity).success)return fail('Inventory capacity exceeded.');this.inventory.add(state.player.inventory,itemId,quantity);state.player.inventory.credits-=price;if(shop.inventorySource==='stock')runtime.stock[itemId]-=quantity;return {success:true,shopId,itemId,quantity,creditsChanged:-price};}const removed=this.inventory.remove(state.player.inventory,itemId,quantity);if(!removed.success)return fail(removed.reason??'Not enough items.');state.player.inventory.credits+=price;if(shop.inventorySource==='stock')runtime.stock[itemId]=(runtime.stock[itemId]??0)+quantity;return {success:true,shopId,itemId,quantity,creditsChanged:price};}
 private price(shop:ShopDefinition,item:Item,mode:'buy'|'sell',state:GameState):number{const rule=mode==='buy'?shop.buyRules:shop.sellRules;let multiplier=rule.priceMultiplier,flat=0;for(const modifier of shop.priceModifiers){const conditions=evaluateConditions(modifier.conditions,{state,contentRegistry:this.content,rollRandom:(min,max)=>this.random.integer(min,max)},this.conditions).allMet;const traits=modifier.requiredPlayerTraits.every(trait=>state.player.traits.includes(trait));const map=!modifier.mapIds.length||modifier.mapIds.includes(state.world.currentMapId);const poi=!modifier.poiIds.length||!!state.world.currentPoiId&&modifier.poiIds.includes(state.world.currentPoiId);if(conditions&&traits&&map&&poi){multiplier*=mode==='buy'?modifier.buyMultiplier:modifier.sellMultiplier;flat+=modifier.flatAdjustment;}}return Math.max(0,Math.round(item.valueCredits*multiplier+flat));}
 private restock(shop:ShopDefinition,state:GameState):void{const runtime=state.shops[shop.id]??={shopId:shop.id,stock:{},lastRestockTurn:state.time.turnCount};if(!shop.restock.enabled||state.time.turnCount-runtime.lastRestockTurn<shop.restock.intervalTurns)return;if(shop.restock.restoreToInitial)for(const entry of shop.inventory)runtime.stock[entry.itemId]=entry.maxQuantity??entry.quantity;runtime.lastRestockTurn=state.time.turnCount;}
}
