import React, { useMemo, useState } from 'react';
import type { GameContent, Quest, QuestStage } from '@neon-ether/game-schema';
import { ArrowRight, CheckCircle2, Play, XCircle } from 'lucide-react';
import { QuestWalkthroughController, type PrerequisiteResult } from '../playtest/QuestWalkthroughController.ts';

const json = (value: unknown) => JSON.stringify(value, null, 2);
export const QuestWalkthrough: React.FC<{ quest: Quest; content: GameContent; onClose: () => void }> = ({ quest, content, onClose }) => {
  const controller = useMemo(() => new QuestWalkthroughController(content, quest), [content, quest]);
  const [, refresh] = useState(0);
  const [prerequisites, setPrerequisites] = useState<PrerequisiteResult[]>([]);
  const [inspectOpen, setInspectOpen] = useState(false);
  const [debugKey, setDebugKey] = useState(''); const [debugValue, setDebugValue] = useState('true');
  const rerender = () => refresh((value) => value + 1);
  const resolved = controller.getResolved();
  const stage = resolved?.stage ?? quest.stages[quest.initialStageId];
  const references = controller.referencesFor(stage);
  const run = (command: () => unknown) => { command(); rerender(); };
  const satisfy = (conditions = [...stage.entryConditions, ...stage.completionConditions]) => { setPrerequisites(controller.satisfyConditions(conditions)); rerender(); };
  const parseValue = (value:string):string|number|boolean => value==='true'?true:value==='false'?false:Number.isNaN(Number(value))?value:Number(value);

  return <div className="fixed inset-0 z-50 overflow-auto bg-[#050713] p-4 text-zinc-200"><header className="mx-auto mb-4 flex max-w-7xl items-center justify-between rounded-xl border border-purple-500/30 bg-black/50 p-4"><div><p className="text-[9px] uppercase tracking-[.25em] text-purple-300">Development-only · production QuestRuntime</p><h1 className="font-bold text-white">Guided Quest Walkthrough // {quest.name}</h1></div><button type="button" onClick={onClose} className="rounded border border-zinc-700 px-3 py-2">Close</button></header>
    <div className="mx-auto grid max-w-7xl gap-4 xl:grid-cols-[260px_1fr_330px]">
      <aside className="rounded-xl border border-zinc-800 bg-black/30 p-3"><p className="mb-2 text-[10px] uppercase text-cyan-300">Stages and paths</p>{(Object.values(quest.stages) as QuestStage[]).sort((a,b)=>a.stageNumber-b.stageNumber).map((candidate)=><button type="button" key={candidate.id} onClick={()=>{setPrerequisites(controller.jumpToStage(candidate.id));rerender();}} className={`mb-1 w-full rounded border p-2 text-left ${candidate.id===stage.id?'border-purple-400 bg-purple-950/30':'border-zinc-800'}`}><span className="text-[9px] text-zinc-500">STAGE {candidate.stageNumber}</span><span className="block text-xs text-white">{candidate.title}</span><span className="block text-[9px] text-zinc-600">{candidate.id}</span></button>)}<button type="button" onClick={()=>setInspectOpen(true)} className="mt-3 w-full rounded border border-amber-500/30 p-2 text-xs text-amber-300">Debug Inspector</button></aside>
      <main className="space-y-3 rounded-xl border border-zinc-800 bg-black/30 p-4"><header className="flex flex-wrap items-center justify-between gap-2"><div><p className="text-[9px] uppercase text-purple-300">Current stage</p><h2 className="text-lg font-bold text-white">{stage.stageNumber}. {stage.title}</h2><p className="text-xs text-zinc-400">{stage.journalEntry}</p></div><div className="flex gap-2">{!resolved&&<button type="button" onClick={()=>run(()=>controller.start())} className="rounded border border-amber-500/40 px-3 py-2 text-xs text-amber-300">Retry Start Quest</button>}<button type="button" onClick={()=>satisfy()} className="rounded border border-emerald-500/40 px-3 py-2 text-xs text-emerald-300">Satisfy Conditions</button><button type="button" onClick={()=>{setPrerequisites(controller.satisfyCurrentStage());rerender();}} className="rounded border border-cyan-500/40 px-3 py-2 text-xs text-cyan-300">Complete Objectives</button></div></header>
        <p className={`rounded border p-2 text-[10px] ${resolved?.canCompleteStage?'border-emerald-500/30 text-emerald-300':'border-amber-500/30 text-amber-300'}`}>Stage progression: {resolved?.canCompleteStage?'ready to continue':'Previous/current stage incomplete — complete required objectives and completion conditions.'}</p>
        <Panel title="Objectives">{stage.objectives.length?stage.objectives.map((objective)=><div key={objective.id} className="mb-1 rounded border border-zinc-800 p-2 text-xs"><b className="text-white">{objective.description}</b><span className="ml-2 text-zinc-500">{objective.objectiveType} · {objective.requiredCount} × {objective.targetId ?? 'custom'}</span></div>):<Empty/>}</Panel>
        <div className="grid gap-3 lg:grid-cols-2"><ConditionPanel title="Entry conditions" conditions={stage.entryConditions} controller={controller}/><ConditionPanel title="Completion conditions" conditions={stage.completionConditions} controller={controller}/></div>
        {(prerequisites.length>0||controller.unresolvedPrerequisites.length>0)&&<Panel title="Prerequisite builder result">{prerequisites.map((result,index)=><div key={index} className={`mb-1 flex gap-2 rounded p-2 text-[10px] ${result.satisfied?'bg-emerald-950/20 text-emerald-300':'bg-rose-950/20 text-rose-300'}`}>{result.satisfied?<CheckCircle2 className="h-3.5 w-3.5"/>:<XCircle className="h-3.5 w-3.5"/>}<span><b>{result.condition.type}</b> — {result.reason}{!result.automatic&&' · unresolved; enter a manual value in Debug Inspector'}</span></div>)}{controller.unresolvedPrerequisites.map((warning,index)=><div key={`warning-${index}`} className="mb-1 rounded bg-amber-950/20 p-2 text-[10px] text-amber-300">Unresolved prerequisite — {warning} Use Debug Inspector.</div>)}</Panel>}
        <Panel title="Quest actions">{resolved?.actions.length?resolved.actions.map((action)=><div key={action.id} className="mb-2 rounded border border-zinc-800 p-2"><div className="flex justify-between"><div><b className="text-xs text-white">{action.label}</b><p className="text-[10px] text-zinc-500">{action.isAvailable?'Available':action.unmetReason}</p></div><button type="button" disabled={!action.isAvailable} onClick={()=>run(()=>controller.executeAction(action.id))} className="rounded border border-cyan-500/30 px-2 text-[10px] text-cyan-300 disabled:opacity-30">Run</button></div><pre className="mt-2 overflow-auto text-[9px] text-emerald-300">Effects: {json(action.effects)}{action.targetStageId&&`\nNext: ${action.targetStageId}`}</pre></div>):<Empty/>}</Panel>
        <Panel title="Branches / next stages">{stage.branches.map((branch)=><div key={branch.id} className="mb-2 flex items-center justify-between rounded border border-zinc-800 p-2"><div><b className="text-xs text-white">{branch.label||branch.id}</b><p className="text-[10px] text-zinc-500">{resolved?.branches.find((item)=>item.id===branch.id)?.unmetReason||`→ ${branch.targetStageId}`}</p></div><button type="button" onClick={()=>run(()=>controller.completeStage(branch.id))} disabled={!resolved?.branches.find((item)=>item.id===branch.id)?.isAvailable||!resolved?.canCompleteStage} className="rounded border border-purple-500/30 px-2 py-1 text-[10px] text-purple-300 disabled:opacity-30">Choose</button></div>)}{!stage.branches.length&&<button type="button" onClick={()=>run(()=>controller.completeStage())} disabled={!resolved?.canCompleteStage} className="rounded border border-purple-500/30 px-3 py-2 text-xs text-purple-300 disabled:opacity-30">Continue {stage.nextStageId&&`→ ${stage.nextStageId}`}</button>}</Panel>
        <Panel title="Stage effects and outcome"><pre className="overflow-auto text-[9px] text-emerald-300">Entry: {json(stage.entryEffects)}{`\n`}Completion: {json(stage.completionEffects)}{`\n`}Next: {stage.nextStageId??'quest completion'}</pre></Panel>
      </main>
      <aside className="space-y-3"><Panel title="Relevant Events and Choices">{references.events.map((event)=><div key={event.id} className="mb-2 rounded border border-zinc-800 p-2"><div className="flex justify-between"><b className="text-xs text-white">{event.name}</b><button type="button" onClick={()=>run(()=>controller.playEvent(event.id))} className="text-[10px] text-purple-300"><Play className="inline h-3 w-3"/> Play Event</button></div>{event.steps.flatMap((step)=>step.choices).map((choice)=><p key={choice.id} className="mt-1 text-[9px] text-zinc-500">Choice: {choice.text} · {controller.evaluate(choice.conditions).allMet ? 'available' : controller.evaluate(choice.conditions).failedConditions[0]?.reason}</p>)}</div>)}{!references.events.length&&<Empty/>}</Panel>
        <Panel title="POI references">{references.pois.map((poi)=><button type="button" key={poi.id} onClick={()=>run(()=>controller.openPoi(poi.id))} className="mb-1 w-full rounded border border-zinc-800 p-2 text-left text-xs text-cyan-300">Open POI · {poi.name}</button>)}{!references.pois.length&&<Empty/>}</Panel>
        <Panel title="Encounters">{references.encounters.map((encounter)=><button type="button" key={encounter.id} onClick={()=>run(()=>controller.startEncounter(encounter.id))} className="mb-1 w-full rounded border border-zinc-800 p-2 text-left text-xs text-rose-300">Start Encounter · {encounter.name}</button>)}{!references.encounters.length&&<Empty/>}</Panel>
        <Panel title="Branch history"><div className="space-y-1">{controller.history.map((entry,index)=><div key={entry.id} className="flex items-center gap-1 text-[10px]"><span className="text-purple-300">{entry.label}</span>{index<controller.history.length-1&&<ArrowRight className="h-3 w-3 text-zinc-600"/>}</div>)}</div></Panel>
        <Panel title="State changes"><pre className="max-h-48 overflow-auto whitespace-pre-wrap text-[9px] text-amber-200">{controller.stateChanges.join('\n\n')}</pre></Panel>
      </aside>
    </div>
    {inspectOpen&&<div className="fixed inset-0 z-[60] flex items-center justify-center bg-black/85 p-4"><section className="max-h-[90vh] w-full max-w-4xl overflow-auto rounded-xl border border-amber-500/30 bg-[#070914] p-4"><header className="mb-3 flex justify-between"><div><p className="text-[9px] uppercase text-amber-300">Isolated temporary state</p><h3 className="font-bold text-white">Debug Inspector</h3></div><button onClick={()=>setInspectOpen(false)}>×</button></header><div className="mb-3 grid gap-2 md:grid-cols-3"><input value={debugKey} onChange={(e)=>setDebugKey(e.target.value)} placeholder="flag / item / npc / faction ID" className="rounded border border-zinc-700 bg-black p-2 text-xs"/><input value={debugValue} onChange={(e)=>setDebugValue(e.target.value)} placeholder="value" className="rounded border border-zinc-700 bg-black p-2 text-xs"/><div className="flex flex-wrap gap-1"><button onClick={()=>run(()=>controller.setDebugFlag(debugKey,parseValue(debugValue)))} className="rounded border border-zinc-700 px-2 text-[9px]">Set Flag</button><button onClick={()=>run(()=>controller.addDebugItem(debugKey,Number(debugValue)||1))} className="rounded border border-zinc-700 px-2 text-[9px]">Add Item</button><button onClick={()=>run(()=>controller.setDebugRelationship(debugKey,Number(debugValue)))} className="rounded border border-zinc-700 px-2 text-[9px]">Relationship</button><button onClick={()=>run(()=>controller.setDebugFactionReputation(debugKey,Number(debugValue)))} className="rounded border border-zinc-700 px-2 text-[9px]">Reputation</button></div></div><pre className="text-[9px] text-emerald-300">{json(controller.getState())}</pre></section></div>}
  </div>;
};

const Panel:React.FC<React.PropsWithChildren<{title:string}>>=({title,children})=><section className="rounded-lg border border-zinc-800 bg-black/20 p-3"><h3 className="mb-2 text-[10px] font-bold uppercase text-cyan-300">{title}</h3>{children}</section>;
const Empty=()=> <p className="text-[10px] text-zinc-600">None authored for this stage.</p>;
const ConditionPanel:React.FC<{title:string;conditions:any[];controller:QuestWalkthroughController}>=({title,conditions,controller})=><Panel title={title}>{conditions.length?conditions.map((condition,index)=>{const result=controller.evaluate([condition]);return <div key={index} className={`mb-1 rounded p-2 text-[10px] ${result.allMet?'bg-emerald-950/20 text-emerald-300':'bg-rose-950/20 text-rose-300'}`}><b>{condition.type}</b> · {result.explanation.join('; ')}</div>}):<Empty/>}</Panel>;
