import React, { useMemo, useState } from 'react';
import type { DevelopmentTelemetrySession, TelemetrySystem } from '../telemetry/DevelopmentTelemetry.ts';
import { Download, Trash2 } from 'lucide-react';

const systems: Array<TelemetrySystem|'all'>=['all','combat','economy','progression','quest','event','faction','base','environment','condition'];
const download=(name:string,type:string,data:string)=>{const url=URL.createObjectURL(new Blob([data],{type}));const anchor=document.createElement('a');anchor.href=url;anchor.download=name;anchor.click();URL.revokeObjectURL(url);};
export const TelemetryInspector:React.FC<{telemetry:DevelopmentTelemetrySession;onRefresh:()=>void}>=({telemetry,onRefresh})=>{
  const [system,setSystem]=useState<(typeof systems)[number]>('all');const[entity,setEntity]=useState('');
  const summary=telemetry.getSummary();const events=telemetry.events.filter((event)=>(system==='all'||event.system===system)&&(!entity||`${event.entityId??''} ${JSON.stringify(event.data)}`.toLowerCase().includes(entity.toLowerCase()))).slice().reverse();
  const checks=telemetry.events.filter((event)=>event.type==='skillCheck');const economy=telemetry.events.filter((event)=>event.system==='economy');
  const cards=[['Events',summary.eventCount],['Combats',summary.combats],['W / L',`${summary.victories} / ${summary.defeats}`],['Money +',summary.moneyGained],['Money −',summary.moneySpent],['Skill checks',summary.skillChecks],['Check success',`${Math.round(summary.skillCheckSuccessRate*100)}%`],['Quests done',summary.questsCompleted]];
  return <div className="space-y-3"><header className="flex flex-wrap justify-between gap-2"><div><p className="text-[9px] uppercase tracking-widest text-purple-300">Local development session</p><h3 className="font-bold text-white">Gameplay Balancing Telemetry</h3></div><div className="flex gap-2"><button onClick={()=>download(`${telemetry.sessionId}.json`,'application/json',telemetry.exportJson())} className="rounded border border-cyan-500/40 px-3 py-2 text-xs text-cyan-300"><Download className="mr-1 inline h-3 w-3"/>JSON</button><button onClick={()=>download(`${telemetry.sessionId}.csv`,'text/csv',telemetry.exportCsv())} className="rounded border border-cyan-500/40 px-3 py-2 text-xs text-cyan-300"><Download className="mr-1 inline h-3 w-3"/>CSV</button><button onClick={()=>{telemetry.clear();onRefresh();}} className="rounded border border-rose-500/30 p-2 text-rose-300"><Trash2 className="h-4 w-4"/></button></div></header>
    <div className="grid grid-cols-2 gap-2 md:grid-cols-4 xl:grid-cols-8">{cards.map(([label,value])=><div key={String(label)} className="rounded border border-zinc-800 bg-black/30 p-2"><p className="text-[8px] uppercase text-zinc-500">{label}</p><p className="text-sm font-bold text-white">{value}</p></div>)}</div>
    <div className="grid gap-3 xl:grid-cols-3"><Panel title="Encounter comparison"><pre>{JSON.stringify(telemetry.getEncounterComparison(),null,2)}</pre></Panel><Panel title="Skill check success"><p>{checks.filter((event)=>event.data.passed).length} success / {checks.length} attempted</p><pre>{JSON.stringify(checks.map((event)=>({skill:event.entityId,outcome:event.data.outcome??event.data.result,passed:event.data.passed})),null,2)}</pre></Panel><Panel title="Economy totals"><p>Gained {summary.moneyGained} · Spent {summary.moneySpent}</p><pre>{JSON.stringify(economy.reduce((totals:Record<string,number>,event)=>({...totals,[event.type]:(totals[event.type]??0)+1}),{} as Record<string,number>),null,2)}</pre></Panel></div>
    <div className="grid gap-3 xl:grid-cols-2"><Panel title="Quest choice distribution"><pre>{JSON.stringify(telemetry.getChoiceDistribution(),null,2)}</pre></Panel><Panel title="Filters"><select value={system} onChange={(event)=>setSystem(event.target.value as typeof system)} className="mr-2 rounded border border-zinc-700 bg-zinc-950 p-2 text-xs">{systems.map((value)=><option key={value}>{value}</option>)}</select><input value={entity} onChange={(event)=>setEntity(event.target.value)} placeholder="Filter entity / payload…" className="rounded border border-zinc-700 bg-zinc-950 p-2 text-xs"/></Panel></div>
    <div className="max-h-[330px] overflow-auto">{events.map((event)=><article key={event.id} className="mb-1 grid grid-cols-[80px_90px_130px_1fr] gap-2 rounded border border-zinc-800 p-2 text-[9px]"><span className="text-zinc-600">#{event.id}</span><span className="text-purple-300">{event.system}</span><span className="text-cyan-300">{event.type}</span><span><b>{event.entityId}</b> {JSON.stringify(event.data)}</span></article>)}</div>
  </div>;
};
const Panel:React.FC<React.PropsWithChildren<{title:string}>>=({title,children})=><section className="max-h-56 overflow-auto rounded border border-zinc-800 bg-black/30 p-3 text-[10px] text-zinc-300"><h4 className="mb-2 text-[9px] font-bold uppercase text-cyan-300">{title}</h4>{children}</section>;
