import { GAME_CONTENT_MANIFEST } from '../content/index.ts';
import { CombatEncounterEngine, ContentRegistry, TurnBasedCombatEngine, createInitialGameState } from '../packages/game-runtime/src/index.ts';

const registry = new ContentRegistry();
registry.loadManifest(GAME_CONTENT_MANIFEST);
const state = createInitialGameState();
const tactical = new TurnBasedCombatEngine(registry).createEncounter('enc_prologue_ares_vault_response', state);
if (!tactical) throw new Error('Resolution fixture did not start.');
state.combat = tactical;
state.world.activeEncounterId = tactical.encounterId;
const encounterEngine = new CombatEncounterEngine();
const humans = Object.values(state.combat.combatants).filter((unit) => unit.team === 'Enemy' && registry.getEnemy(unit.sourceId)?.tags.includes('HasMind'));
const mechanical = Object.values(state.combat.combatants).find((unit) => unit.team === 'Enemy' && registry.getEnemy(unit.sourceId)?.tags.includes('Mechanical'));
if (humans.length < 3 || !mechanical) throw new Error('Resolution fixture needs three sentient hostiles and one mechanical hostile.');
Object.assign(humans[0], { currentHp: 0, isDefeated: true, isIncapacitated: false, defeatType: 'Lethal', resolutionState: 'Dead' });
Object.assign(humans[1], { currentHp: 0, isDefeated: true, isIncapacitated: true, defeatType: 'NonLethal', resolutionState: 'Incapacitated' });
Object.assign(humans[2], { isDefeated: true, isIncapacitated: true, defeatType: 'NonLethal', resolutionState: 'Surrendered' });
Object.assign(mechanical, { currentHp: 0, isDefeated: true, isIncapacitated: false, defeatType: 'Lethal', resolutionState: 'Destroyed' });
const resolution = encounterEngine.resolveVictory('enc_prologue_ares_vault_response', state, registry, state.combat.roundNumber);
if (!resolution) throw new Error('Combat resolution was not produced.');
if (resolution.deadEnemies.map((enemy) => enemy.id).join() !== humans[0].id) throw new Error('Dead tactical combatant was not projected.');
if (resolution.destroyedEnemies.map((enemy) => enemy.id).join() !== mechanical.id) throw new Error('Mechanical combatant was not projected as destroyed.');
if (!resolution.surrenderedEnemies.some((enemy) => enemy.id === humans[2].id)) throw new Error('Surrendered tactical combatant was not projected.');
if (!resolution.incapacitatedEnemies.some((enemy) => enemy.id === humans[1].id && enemy.status === 'Incapacitated')) throw new Error('Incapacitated sentient was not exposed for post-combat actions.');
if (!resolution.incapacitatedEnemies.some((enemy) => enemy.id === humans[2].id && enemy.status === 'Surrendered')) throw new Error('Surrendered sentient was not exposed for post-combat actions.');
if (resolution.incapacitatedEnemies.some((enemy) => enemy.id === mechanical.id)) throw new Error('Destroyed mechanical enemy became a prisoner.');
const postCombat = encounterEngine.executePostCombatAction(humans[1].id, 'Restrain', state, registry);
if (postCombat.actionId !== 'Restrain' || resolution.incapacitatedEnemies.find((enemy) => enemy.id === humans[1].id)?.status !== 'Restrained') throw new Error('Surviving sentient did not enter the existing post-combat action flow.');
console.log('Tactical dispositions projected into post-combat resolution without fabricated prisoners.');
