import {ContentRegistry,GameSession} from '../packages/game-runtime/src/index.ts';import {GAME_CONTENT_MANIFEST} from '../content/index.ts';
const registry=new ContentRegistry();registry.loadManifest(GAME_CONTENT_MANIFEST);const session=new GameSession(registry);
const advanceEvent=()=>{while(session.getState().world.mode==='Event')session.advanceEventStep()};
if(!session.startEvent('evt_new_game_intro'))throw Error('new-game intro did not start');advanceEvent();let state=session.getState();if(state.world.currentPoiId!=='poi_prologue_service_entrance')throw Error('intro did not reach the service entrance');if(!session.executePoiAction('poi_prologue_service_entrance','act_prologue_enter_with_team').success)throw Error('service entrance action unavailable');advanceEvent();state=session.getState();
if(state.world.currentPoiId!=='poi_prologue_warehouse'||!['npc_prologue_companion_female','npc_prologue_companion_male'].every(id=>state.companions.includes(id)))throw Error('service entrance did not establish the party/warehouse flow');
const creditsBefore=state.player.inventory.credits;const loot=session.executePoiAction('poi_prologue_warehouse','act_prologue_search_lockers');if(!loot.success)throw Error('warehouse lockers unavailable');state=session.getState();if(state.player.inventory.credits!==creditsBefore+65||!state.player.inventory.items.some(item=>item.itemId==='con_trauma_patch')||!state.player.inventory.items.some(item=>item.itemId==='wpn_ether_baton'))throw Error('warehouse loot mismatch');session.dismissActionResolution();
session.openPoi('poi_prologue_maintenance_office');if(!session.executePoiAction('poi_prologue_maintenance_office','act_prologue_breach_maintenance_node').success)throw Error('maintenance breach unavailable');state=session.getState();if(state.world.mode!=='Minigame'||!state.world.activeMinigame)throw Error('Match Values did not launch');
const minigame=state.world.activeMinigame,target=['6A','93','45'];function path(buffer=Array<any>(),axis:'row'|'column'='row',index=0,used=new Set<string>()):any[]|undefined{if(buffer.length>=3&&target.every((v,i)=>buffer.slice(-3)[i]?.value===v))return buffer;if(buffer.length>=minigame.bufferCapacity)return;for(const row of minigame.matrix)for(const cell of row){if(used.has(cell.id)||(axis==='row'?cell.row!==index:cell.column!==index))continue;const found=path([...buffer,cell],axis==='row'?'column':'row',axis==='row'?cell.column:cell.row,new Set([...used,cell.id]));if(found)return found}}const route=path();if(!route)throw Error('deterministic puzzle has no legal data-cache route');for(const cell of route)session.selectMinigameCell(cell.row,cell.column);const beforeBreach=session.getState().player.inventory.credits,result=session.finishMinigame();state=session.getState();if(result?.status!=='partialSuccess'||result.completedSequenceIds.join(',')!=='payload_data_cache'||state.player.inventory.credits!==beforeBreach+90||state.world.flags['prologue.security_route_discovered'])throw Error('target rewards were not independent');session.dismissActionResolution();
session.openPoi('poi_prologue_freight_access');if(!session.executePoiAction('poi_prologue_freight_access','act_prologue_enter_deeper_facility').success)throw Error('freight transition unavailable');advanceEvent();state=session.getState();if(state.world.flags['prologue.region_1_completed']!==true||state.quests['qst_prologue_ares_vault']?.currentStageId!=='stage_03_freight_access')throw Error('Region 1 did not complete');console.log('Prologue Region 1 playable flow passed');
