import type { CharacterCreationSelection } from '../packages/game-schema/src/index.ts';
import { ContentRegistry, GameSession } from '../packages/game-runtime/src/index.ts';
import { GAME_CONTENT_MANIFEST } from '../content/index.ts';

const registry = new ContentRegistry();
registry.loadManifest(GAME_CONTENT_MANIFEST);
const session = new GameSession(registry);
const options = session.getCharacterCreationOptions();
const definition = options.definition;
if (!definition || !options.backgrounds.length || !options.races.length || !options.classes.length || definition.startingPerkCount > options.perks.length) throw new Error('Character creation content is incomplete.');
let attributePoints = definition.attributePointBudget;
const attributes = Object.fromEntries(definition.attributeRules.map((rule) => {
  const purchased = Math.min(rule.maximum - rule.minimum, Math.floor(attributePoints / rule.costPerPoint));
  attributePoints -= purchased * rule.costPerPoint;
  return [rule.attribute, rule.minimum + purchased];
}));
let skillPoints = definition.skillPointBudget;
const skills = Object.fromEntries(definition.skillRules.map((rule) => {
  const purchased = Math.min(rule.maximum - rule.minimum, Math.floor(skillPoints / rule.costPerRank));
  skillPoints -= purchased * rule.costPerRank;
  return [rule.skillId, rule.minimum + purchased];
}));
const playableClass=options.classes.find(value=>value.availability!=='NPC')!;
const npcOnlyClass=options.classes.find(value=>value.availability==='NPC');if(!npcOnlyClass)throw new Error('NPC-only class fixture is missing.');
const selection: CharacterCreationSelection = { name:'Rook', age:definition.defaultAge, portraitId:definition.portraits[0]?.id, raceId:definition.defaultRaceId, classId:playableClass.id, backgroundId:options.backgrounds[0].id, attributes: attributes as CharacterCreationSelection['attributes'], skills, perkIds:options.perks.filter((perk) => !perk.requiredBackgroundIds.length || perk.requiredBackgroundIds.includes(options.backgrounds[0].id)).slice(0,definition.startingPerkCount).map((perk) => perk.id) };
if(selection.raceId!=='race_human'||options.races.find(value=>value.id===selection.raceId)?.availability==='NPC')throw new Error('Human is not the available default race.');
const disabledRace=options.races.find(value=>value.availability==='NPC');if(!disabledRace)throw new Error('Disabled race fixture is missing.');
if(session.validateCharacterCreation({...selection,raceId:disabledRace.id}).valid)throw new Error('A disabled race was selectable.');
const orc=registry.getCharacter('npc_ash_crow')!,resolvedOrc=session.getResolvedNpcCharacter(orc.id)!;if(orc.raceId!=='race_orc'||resolvedOrc.attributes.body!==orc.attributes.body+2||resolvedOrc.vitals.maxHp!==orc.vitals.maxHp+4)throw new Error('NPC Orc racial modifiers did not resolve.');
const elf=registry.getCharacter('npc_mira_vesk')!,resolvedElf=session.getResolvedNpcCharacter(elf.id)!;if(elf.raceId!=='race_elf'||!resolvedElf.traits.includes('Elven Reflexes')||!resolvedElf.traits.includes('HasMind'))throw new Error('NPC Elf racial traits did not resolve.');
const darkElf=session.getResolvedNpcCharacter('npc_doctor_sable')!;if(darkElf.raceId!=='race_dark_elf'||!darkElf.traits.includes('Dark-Ether Sensitivity'))throw new Error('NPC Dark Elf identity did not resolve while Player-unavailable.');
const classSignatureIds=new Set(options.classes.flatMap(value=>value.startingAbilityIds));if(options.races.some(race=>race.grantedAbilityIds.some(id=>classSignatureIds.has(id))))throw new Error('Race content grants a Primary Class signature ability.');
const hybridBase=registry.getCharacter('npc_warden_kest')!,hybrid=session.getResolvedNpcCharacter(hybridBase.id)!;if(hybrid.raceId!=='race_human_elf_lineage'||hybrid.attributes.reflexes!==hybridBase.attributes.reflexes+1||hybrid.attributes.presence!==hybridBase.attributes.presence+1||hybrid.vitals.maxEther!==hybridBase.vitals.maxEther)throw new Error('Hybrid lineage did not use its direct authored modifiers.');
if(!session.evaluateConditions([{type:'raceIs',raceId:'race_human'},{type:'raceHasTag',tag:'HumanLineage'}]).allMet||!session.evaluateConditions([{type:'raceIs',raceId:'race_orc',targetCharacterId:'npc_ash_crow'},{type:'raceHasTag',tag:'Resilient',targetCharacterId:'npc_ash_crow'}]).allMet)throw new Error('Generic race Conditions did not resolve Player and NPC lineages.');
if(session.validateCharacterCreation({...selection,classId:npcOnlyClass.id}).valid)throw new Error('An NPC-only class was selectable by the Player.');
const overspent={...selection,attributes:{...selection.attributes,body:definition.attributeRules.find(value=>value.attribute==='body')!.maximum,reflexes:definition.attributeRules.find(value=>value.attribute==='reflexes')!.maximum}};
const overspentValidation=session.validateCharacterCreation(overspent);if(overspentValidation.valid||overspentValidation.attributePointsRemaining<0)throw new Error('Attribute budget invariant failed.');
if(session.initializeNewGame(overspent).valid)throw new Error('Invalid attribute allocation was confirmed.');
let allocation={...selection,attributes:Object.fromEntries(definition.attributeRules.map(rule=>[rule.attribute,rule.minimum])) as CharacterCreationSelection['attributes']};
for(let index=0;index<100;index+=1){const rule=definition.attributeRules[index%definition.attributeRules.length];allocation=session.adjustCharacterCreationAttribute(allocation,rule.attribute,1);if(session.validateCharacterCreation(allocation).attributePointsRemaining<0)throw new Error('Attribute interaction produced a negative budget.');}
const generatedName=session.generateCharacterName();const authoredNames=registry.namePools.getAll().flatMap(pool=>pool.firstNames.flatMap(first=>pool.surnames.length?pool.surnames.map(surname=>`${first} ${surname}`):[first]));if(!authoredNames.includes(generatedName)||generatedName.length>40)throw new Error('Random name generator did not use an authored name pool.');
const manualNameSelection={...selection,name:'Manual Vane'};if(session.initializeNewGame(manualNameSelection).valid!==true||session.getState().player.name!=='Manual Vane')throw new Error('Manual name edit after randomization was not preserved.');
const validation = session.initializeNewGame(selection);
if (!validation.valid) throw new Error(validation.reasons.join(' '));
const created = session.getState();
if (created.player.name !== selection.name || created.player.age !== selection.age || created.player.raceId !== selection.raceId || created.player.classId !== selection.classId || created.player.backgroundId !== selection.backgroundId) throw new Error('Created identity was not applied.');
if(!playableClass.startingAbilityIds.every(id=>created.player.abilityIds.includes(id)))throw new Error('Class signature ability was not granted.');
if(new Set(created.player.abilityIds).size!==created.player.abilityIds.length)throw new Error('Starting abilities contain duplicates.');
for(const starting of [...playableClass.startingEquipment,...options.backgrounds[0].startingItems])if(created.player.inventory.items.filter(entry=>entry.itemId===starting.itemId).reduce((sum,entry)=>sum+entry.quantity,0)!==starting.quantity)throw new Error(`Starting equipment quantity is invalid for ${starting.itemId}.`);
if(!created.player.traits.includes('Human Adaptability')||!created.player.traits.includes('HasMind'))throw new Error('Human racial traits were not applied.');
if(created.player.specialPathIds.length)throw new Error('A locked story Special Path leaked into New Game.');
if(created.world.flags['origin.street']!==true)throw new Error('Background effects were not applied alongside class effects.');
const mindmancerIds=new Set(registry.abilities.findByTag('Mindmancer').map(value=>value.id));
const startingAbilityIds=[...options.races.flatMap(value=>[...value.grantedAbilityIds,...value.startingEffects.filter(effect=>effect.type==='setAbilityUnlocked').map(effect=>effect.abilityId)]),...options.classes.filter(value=>value.availability!=='NPC').flatMap(value=>[...value.startingAbilityIds,...value.startingEffects.filter(effect=>effect.type==='setAbilityUnlocked').map(effect=>effect.abilityId)]),...options.backgrounds.flatMap(value=>value.startingEffects.filter(effect=>effect.type==='setAbilityUnlocked').map(effect=>effect.abilityId)),...options.perks.flatMap(value=>value.startingEffects.filter(effect=>effect.type==='setAbilityUnlocked').map(effect=>effect.abilityId))];
if(startingAbilityIds.some(id=>mindmancerIds.has(id)))throw new Error('Starting content grants a Mindmancer ability.');
if (definition.startingEventId && created.world.mode !== 'Event') throw new Error('Configured prologue did not start.');
session.advanceEventStep();
if (session.getState().world.activeEventStepId !== 'intro_street') throw new Error('Background-conditioned intro variant was not selected.');
while (session.getState().world.mode === 'Event') session.advanceEventStep();
const completed = session.getState();
if (completed.world.mode !== 'POI' || completed.world.currentPoiId !== definition.startingPoiId || completed.world.flags['intro.completed'] !== true) throw new Error('Prologue did not complete into the configured gameplay origin.');
const skippedSession = new GameSession(registry);
if (!skippedSession.initializeNewGame(selection).valid || !skippedSession.skipEvent()) throw new Error('Explicit intro skip failed.');
const skipped = skippedSession.getState();
if (skipped.world.mode !== completed.world.mode || skipped.world.currentPoiId !== completed.world.currentPoiId || skipped.world.flags['intro.completed'] !== true) throw new Error('Skip did not apply the mandatory completion state.');
const serialized = session.serializeSave();
const restored = new GameSession(registry);
if (!restored.loadSave(serialized).success) throw new Error('Created character save failed to load.');
const loaded = restored.getState();
if (loaded.player.name !== selection.name || loaded.player.age !== selection.age || loaded.player.raceId !== selection.raceId || loaded.player.classId !== selection.classId || loaded.player.backgroundId !== selection.backgroundId || !selection.perkIds.every(id=>loaded.player.perks.includes(id)) || !playableClass.startingAbilityIds.every(id=>loaded.player.abilityIds.includes(id))) throw new Error('Character creation was not preserved by save/load.');
const npcContent=structuredClone(GAME_CONTENT_MANIFEST);const npcFixture=npcContent.npcs.find(value=>value.id==='npc_ash_crow')!;npcFixture.classId=npcOnlyClass.id;const npcRegistry=new ContentRegistry();npcRegistry.loadManifest(npcContent);const resolvedNpc=new GameSession(npcRegistry).getResolvedNpcCharacter(npcFixture.id);if(!resolvedNpc||!npcOnlyClass.startingAbilityIds.every(id=>resolvedNpc.abilityIds.includes(id)))throw new Error('NPC class abilities did not resolve through the existing character resolver.');
console.log('Character creation → initializer → prologue → save/load passed.');
